<link rel="stylesheet" href="<?php echo $this->basePath() ?>/plugins/jquery-file-upload/css/style.css">
<!-- blueimp Gallery styles -->
<!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/plugins/jquery-file-upload/css/jquery.fileupload.css">
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/plugins/jquery-file-upload/css/jquery.fileupload-ui.css">

<div class="form-group">
    <label class="col-md-2 control-label">Images</label>
    <div class="col-md-10">
        <!-- The file upload form used as target for the file upload widget -->
        <div class="fileupload" data-id="<?php echo $this->dataId ?>" data-code="<?php echo $this->code ?>">
            <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
            <div class="row fileupload-buttonbar">
                <div class="col-lg-9">
                    <!-- The fileinput-button span is used to style the file input field as button -->
                        <span class="btn btn-success btn-sm fileinput-button">
                            <i class="glyphicon glyphicon-plus"></i>
                            <span>Séléctionner image(s)</span>
                            <input type="file" name="files[]" multiple>
                        </span>
                    <button type="submit" class="btn btn-primary btn-sm start">
                        <i class="glyphicon glyphicon-upload"></i>
                        <span>Démarrer téléchargement</span>
                    </button>
                    <button type="reset" class="btn btn-warning btn-sm cancel">
                        <i class="glyphicon glyphicon-ban-circle"></i>
                        <span>Annuler</span>
                    </button>
                    <!-- <button type="button" class="btn btn-danger delete">
                        <i class="glyphicon glyphicon-trash"></i>
                        <span>Supprimer</span>
                    </button>
                    <input type="checkbox" class="toggle"> -->
                    <!-- The global file processing state -->
                    <span class="fileupload-process"></span>
                </div>
                <!-- The global progress state -->
                <div class="col-lg-3 fileupload-progress fade">
                    <!-- The global progress bar -->
                    <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                        <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                    </div>
                    <!-- The extended global progress state -->
                    <div class="progress-extended">&nbsp;</div>
                </div>
            </div>
            <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
        </div>
    </div>
</div>