<div class="shell" style="background: white">
    <div class="row" style="padding-top: 50px; text-align: center">
        <form aciton="<?php echo $this->url('home/forgotpassword', array('lang'=>$this->lang_id)); ?>" method="POST">
            <div class="row">
                <div class="col-xs-12" style="margin-left: auto; margin-right: auto; padding: 10px;font-size: 30px; font-family: Lato-bold;float: none; margin-bottom: 10px;">
                    <?php echo $this->translate("Merci de bien vouloir renseigner votre adresse mail", $this->lang_id); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <label for="email" class="col-xs-3"><?php echo $this->translate("Email", $this->lang_id); ?></label>
                    <div class="col-xs-5" style="text-align: center">
                        <input type="email" id="email" name="email"  class="form-control form-input"/>
                    </div>
                    <div class="col-xs-4" style="text-align: center">
                        <input type="submit" class="form-control" value="Valider" style="width: 150px"/>
                    </div>
                </div>
            </div>
            
            <div style="clear:both"></div>
        </form>
        <div style="padding: 30px 0">
            <a href="<?php echo $this->url('home', array('lang' => $this->lang_id)); ?>"><?php echo $this->translate("Retour", $this->lang_id); ?></a>
        </div>
        <div style="clear:both"></div>
    </div>
</div>
