<div class="main">
    <div class="shell">
        <div class="corps_member">
            <div class="row">
                <div class="col-xs-6">
                    <div class="part_ident">
                        <form id="member_login" method="POST" action="<?php echo $this->url('home/membre/login'); ?>">
                            <div class="tite_member_login"><?php echo $this->translate("Identifiez-vous", $this->lang_id); ?></div>
                            <div><input class="input_member_login" type='text' name="email" placeholder="Votre email" /></div>
                            <div><input class="input_member_login" type='password' name="password" placeholder="Votre mot de passe" /></div>
                            <div><input type="checkbox" value="souvenir"> <?php echo $this->translate("Se souvenir de moi", $this->lang_id); ?></div>
                            <a href="#" ><div class="btn_connection_member"><?php echo $this->translate("Se connecter", $this->lang_id); ?></div></a>
                            <div><a href=""><?php echo $this->translate("J'ai oublié mon mot de passe", $this->lang_id); ?></a></div>
                        </form>
                    </div>
                </div> 
                <div class="col-xs-6">
                    <div class="part_crea">
                        <div class="tite_member_login"><?php echo $this->translate("Inscivez-vous", $this->lang_id); ?></div>
                        <div><?php echo $this->translate("Créer votre compte pour gérer vos lots favoris, vous inscrire aux ventes et commencer à enchérir dès maintenant sur des centaines de lots à pris exceptionnels", $this->lang_id); ?></div>
                        <a href="<?php echo $this->url('home/membre/edit'); ?>"><div class="btn_connection_member"><?php echo $this->translate("S'inscrire maintenant", $this->lang_id); ?></div></a>
                    </div>
                </div> 
            </div>  
        </div>
    </div>
</div>

<script type="text/javascript">
    $('#member_login a').unbind('click').on('click', function(e){
        e.preventDefault();
        $(this).parents('form').submit();
    });
</script>