<div class="main">
    <div class="shell">
        <div class="corps_member">
            <div class="row">
                <div class="col-xs-6">
                    <div class="part_ident">
                        <form id="member_login" method="POST" action="<?php echo $this->url('home/membre/login'); ?>">
                            <div class="tite_member_login">Identifiez-vous</div>
                            <div><input class="input_member_login" type='text' name="email" placeholder="Votre email" /></div>
                            <div><input class="input_member_login" type='password' name="password" placeholder="Votre mot de passe" /></div>
                            <div><input type="checkbox" value="souvenir"> Se souvenir de moi</div>
                            <a href="#" ><div class="btn_connection_member">Se connecter</div></a>
                            <div><a href="">J'ai oublié mon mot de passe</a></div>
                        </form>
                    </div>
                </div> 
                <div class="col-xs-6">
                    <div class="part_crea">
                        <div class="tite_member_login">Inscivez-vous</div>
                        <div>Créer votre compte pour gérer vos lots favoris, vous inscrire aux ventes et commencer à enchérir dès maintenant sur des centaines de lots à pris exceptionnels</div>
                        <a href="<?php echo $this->url('home/membre/edit'); ?>"><div class="btn_connection_member">S'inscrire maintenant</div></a>
                    </div>
                </div> 
            </div>  
        </div>
    </div>
</div>

<script type="text/javascript">
    $('#member_login a').unbind('click').on('click', function(e){
        e.preventDefault();
        $(this).parents('form').submit();
    });
</script>