<div class="shell" style="background: white">
    <div class="row" style="padding-top: 50px; text-align: center">
        <div class="col-xs-5" style="margin-left: auto; margin-right: auto; padding: 10px;font-size: 30px; font-family: Lato-bold;float: none; margin-bottom: 10px;">
            <?php echo $this->translate('La sauvegarde a été effectuée avec succès, un email vient de vous être envoyé afin de valider votre identité', $this->lang_id); ?>
        </div>
    </div> 
    <div class="row" style="padding-top: 50px; font-size: Lato-light;text-align: center; padding-bottom: 30px;">
        <a href="<?php echo $this->url('home', array('lang' => $this->lang_id)); ?>">Retour</a>
    </div>
</div>