<?php

$form = $this->form;
$form->prepare();
$elements = $form->getElements();
?>


<div class="tab-pane fade <?php echo $this->class ?>" id="tab_<?php echo $this->code ?>">
    <?php foreach ($elements as $element): ?>
        <div class="form-group">
            <label class="col-md-2 control-label"><?php echo $element->getLabel() ?></label>
            <div class="col-md-10">
                <?php
                switch ($element->getAttribute('type')):
                    case 'text':

                        echo $this->formInput($form->get($element->getName()));
                        break;
                    case 'hidden':
                        echo $this->formHidden($form->get($element->getName()));
                        break;
                    case 'select':
                        echo $this->formSelect($form->get($element->getName()));
                        break;
                    case 'textarea':
                        echo $this->formTextarea($form->get($element->getName()));
                        break;

                    default:
                        echo $this->formInput($form->get($element->getName()));
                endswitch; ?>
                <span class="help-block"><?= $element->getOption('help') ?></span>
            </div>
        </div>
    <?php endforeach; ?>
</div>