<?php

$_is_searchable = false;

foreach($this->cols as $col){
    if((isset($col['searchable']) && $col['searchable'] === true)){
        $_is_searchable = true;
        break;
    }
}

?>
<!-- Begin: life time stats -->
<div class="portlet">
    <div class="portlet-title" <?php if (empty($this->title)): ?>style="border-bottom:none;"<?php endif; ?>>
        <?php if($this->title): ?>
        <div class="caption">
            <i class="fa fa-gift"></i><?php echo $this->title ?>
        </div>
        <?php endif; ?>
        <?php if($links = $this->links):?>
        <div class="actions">
            <div class="btn-group">
                <a class="btn default yellow-stripe" href="#" data-toggle="dropdown">
                    <i class="fa fa-share"></i> Outils <i class="fa fa-angle-down"></i>
                </a>
                <ul class="dropdown-menu pull-right">
                    <?php foreach($links as $link):?>
                    <li>
                        <?php

                        $params = (isset($link['params']))?$link['params']:array();
                        if((isset($link['route']))){
                                $url = $this->url($link['route'], $params);
                            }else{
                                $url = null;
                            }
                        ?>
                        <?php if($url):?>
                        <a <?php echo (isset($link['attributes']))? $link['attributes'] : ''; ?> href="<?php echo $url ?>">
                            <?php echo $link['label']?>
                        </a>
                        <?php endif; ?>
                    </li>
                    <?php endforeach?>
                </ul>
            </div>
        </div>
        <?php endif; ?>
    </div>
    <div class="portlet-body">
        <div class="table-container">
        <form method="POST" id="datatable_ajax_wrapper" class="dataTables_wrapper dataTables_extended_wrapper" role="grid">

                <?php if(!empty($this->extra_fields)):?>
                <div class="portlet">
                    <?php foreach($this->extra_fields as $field):?>
                        <?php echo $field ?>
                    <?php endforeach;?>
                    </div>
                <?php endif; ?>

                <div class="row">

                    <?php if($this->pagination_available):?>
                    <?php echo $this->paginator ?>
                    <?php endif;?>
                    <div class="col-md-4 col-sm-12">
                       <?php if($this->mass_update_available):?>
                           <div class="table-group-actions pull-right">
                                <span>

                                </span>
                                <select class="table-group-action-input form-control input-inline input-small input-sm">
                                    <option value="">Select...</option>
                                    <option value="publish">Publish</option>
                                    <option value="unpublished">Un-publish</option>
                                    <option value="delete">Delete</option>
                                </select>
                                <button class="btn btn-sm yellow table-group-action-submit"><i class="fa fa-check"></i> Submit</button>
                            </div>
                       <?php  endif;  ?>
                        <?php if($this->actions):?>
                            <?php foreach($this->actions as $action):

                                if(isset($action['route']) && $action['route']){
                                    $params = (isset($action['params']) && !empty($action['params']))?$action['params']: array();
                                    $link = $this->url($action['route'], $params);
                                }else{
                                    $link = '#';
                                }
                                 ?>
                                <?php if($link):?>
                                <a href="<?php echo $link ?>" <?php echo (isset($action['id']))?'id="'.$action['id'].'"':''; ?> <?php echo (isset($action['attributes']))? $action['attributes']:'' ?>  class="btn btn-sm yellow"><i class="fa fa-check"></i> <?php echo $action['label']?></a>
                                <?php endif;?>
                            <?php  endforeach;  ?>
                        <?php  endif;  ?>
                    </div>
                    <div id="datatable_products_processing" class="dataTables_processing" style="visibility: hidden;"><img src="<?php echo $this->basePath() ?>/img/loading-spinner-grey.gif"><span>&nbsp;&nbsp;Loading...</span></div></div>

                    <div class="table-scrollable">
                    <?php if(!empty($this->cols)):?>

                        <table id="datatable_products" class="table table-striped table-bordered table-hover dataTable" aria-describedby="datatable_products_info">
                        <thead>
                        <tr role="row" class="heading">
                            <?php if($this->mass_update_available):?>
                            <th width="1%">
                                <input type="checkbox" class="group-checkable">
                            </th>
                            <?php endif; ?>

                            <?php foreach($this->cols as $col): ?>
                            <th width="<?php echo ($col['width'])?$col['width']:'50'?>%">

                                <?php if(isset($col['sortable']) && $col['sortable'] === true):?>
                                    <div class="table-order-container">
                                        <a class="<?php echo (isset($_GET['direction']) && $_GET['direction'] == 'ASC' && isset($_GET['order']) && $_GET['order'] == $col['code'])?'order-asc-table-on':'order-asc-table-off'?>" href="<?php echo $this->current_url . '?order='.$col['code'].'&direction=ASC' ;?>"></a>
                                        <a class="<?php echo (isset($_GET['direction']) && $_GET['direction'] == 'DESC' && isset($_GET['order']) && $_GET['order'] == $col['code'])?'order-desc-table-on':'order-desc-table-off'?>" href="<?php echo $this->current_url . '?order='.$col['code'].'&direction=DESC' ;?>"></a>
                                    </div>
                                <?php endif; ?>
                                <?php echo $col['label'] ?>
                            </th>
                            <?php endforeach;?>
                        </tr>
                        <?php if($_is_searchable === true):?>
                        <tr role="row" class="filter">
                            <?php if($this->mass_update_available):?>
                            <td>
                            </td>
                            <?php endif; ?>
                            <?php foreach($this->cols as $col):

                                if(!isset($col['searchable']) || !$col['searchable'] && !($col['code'] == "action")):?>

                                    <td>&nbsp;</td>
                                    <?php
                                        continue;
                                 endif; ?>
                                <?php if($col['code'] == "action" && $this->filters_available):?>
                                <td rowspan="1" colspan="1">
                                    <div class="margin-bottom-5">
                                        <button type="submit" class="btn btn-sm yellow filter-submit margin-bottom"><i class="fa fa-search"></i> Rechercher</button>
                                    </div>

                                        <button class="btn btn-sm red filter-cancel"><i class="fa fa-times"></i> Réinitialiser</button>


                                </td>
                                <?php endif; ?>

                                <?php switch ($col['type']){
                                    case 'text':?>
                                        <td>
                                            <input <?php echo (isset($col['placeholder']) && $col['placeholder'] != '')?'placeholder="'.$col['placeholder'].'"':'' ?> value="<?php echo (isset($this->filters['filters'][$col['code']]))?$this->filters['filters'][$col['code']]:'' ?>" type="text" class="form-control form-filter input-sm" name="filters[<?php echo $col['code']?>]" />
                                        </td>
                                    <?php
                                    break;
                                    case 'select':?>
                                        <td>
                                            <select name="product_category" class="form-control form-filter input-sm">
                                                <option value="">Select...</option>
                                            </select>
                                        </td>
                                    <?php
                                    break;



                                    default:{
                                        // ...
                                    }
                                    } ?>

                            <?php endforeach;?>

                        </tr>
                        <?php endif;?>

                        </thead>
                        <tbody>

                        <?php


                        foreach($this->items as $item): ?>

                         <tr class="even">
                             <?php if($this->mass_update_available):?>
                             <td class="">
                                 <div class="checker">
                                    <span>
                                        <input type="checkbox" value="2" name="id[]">
                                    </span>
                                 </div>
                             </td>
                             <?php endif; ?>
                            <?php  foreach($this->cols as $col):



                                if(isset($col['index']) && $col['index']){
                                    $t = $item->$col['code'];
                                    //var_dump($t);die;
                                    $value = (isset($t[$col['index']]))?$t[$col['index']]:'';
                                }else{
                                    if($col['type'] == 'date'){

                                        switch ($col['option']){
                                            case 'formated_current_date':
                                                $value = $this->layout()->getOption("dataHelper")->formatedDateCurrent($item->$col['code']);
                                            break;
                                            default:{

                                            }
                                        }
                                    }else{



                                        $value = $item->$col['code'];
                                    }

                                }

                                ?>
                                <?php if($col['code'] == "action" && !empty($col['items'])): ?>
                                 <td class="">
                                     <?php  foreach($col['items'] as $action):

                                         if(isset($action['type']) && $action['type'] == 'boolean'){
                                             $params = array();

                                             foreach($action['matching_params'] as $param){

                                                 if(isset($item->$param)) $params[$param] = $item->$param;
                                             }

                                             if(isset($action['params_sup']) && !empty($action['params_sup'])){
                                                 foreach($action['params_sup'] as $k=>$v){
                                                     $params[$k] = $v;
                                                 }
                                             }
var_dump($params);
                                             //
                                            $link = $this->url($action['route'], $params);

                                             ?>
                                             <?php if($link && !$item->isModerate):
                                                  if($item->$action['code']){
                                                      $label = ($item->$action['code'])?(isset($action['options'][1]['label']))?$action['options'][1]['label']:'Activé':'';
                                                      $class = (isset($action['options'][1]['class']))?$action['options'][1]['class']:'available';

                                                  }else{
                                                      $label = (isset($action['options'][0]['label']))?$action['options'][0]['label']:'Désactivé';
                                                      $class = (isset($action['options'][0]['class']))?$action['options'][0]['class']:'unavailable';
                                                  }?>
                                                 <a <?php echo (isset($params['id']))?'id="'.$params['id'].'"':''?> class="<?php echo $action['route'] ?> <?php echo $class?>" href="<?php echo (!isset($action['click']) || $action['click'] == true)?$link:'#'?>"><?php echo $label ?></a>
                                             <?php endif;
                                         }else{
                                             $params = array();

                                             foreach($action['matching_params'] as $param){
                                                 if(isset($item->$param)) $params[$param] = $item->$param;
                                             }

                                             if(isset($action['params_sup']) && !empty($action['params_sup'])){
                                                 foreach($action['params_sup'] as $k=>$v){
                                                     $params[$k] = $v;
                                                 }
                                             }

                                            $link = $this->url($action['route'], $params);

                                             ?>
                                             <?php if($link):?>
                                                 <a <?php echo (isset($params['id']))?'id="'.$params['id'].'"':''?> class="<?php echo $action['route'] ?> btn btn-xs default btn-editable <?php echo (isset($action['class']))?$action['class']:'' ?>" href="<?php echo (!isset($action['click']) || $action['click'] == true)?$link:'#'?>"><i class="fa fa-pencil"></i> <?php echo $action['label'] ?></a>
                                             <?php else: ?>
                                                 <?php
                                                 $label = null;
                                                 $class = null;
                                                 $status = null;
                                                 if ($item->isModerate) {
                                                     foreach (json_decode($item->data, true) as $languageCode => $content) {
                                                         if (!empty($content['status']) && !empty($action['options'][$content['status']])) {
                                                             $label = $action['options'][$content['status']]['label'];
                                                             $class = $action['options'][$content['status']]['class'];
                                                             $status = $content['status'];
                                                         }
                                                     }
                                                 }

                                                 ?>
                                                 <?php if ($item->isModerate && $item->status == 0 && $status != null) { ?>
                                                     <a class="<?= $class ?>" href="#"><?= $label ?></a>
                                                     <div style="display: none" id="json-data"><?= $item->data ?></div>
                                                     <div style="display: none" id="logging_id"><?= $item->logging_id ?></div>
                                                     <div style="display: none" id="contract_id"><?= $item->contractId ?></div>
                                                 <?php } elseif ($item->isModerate && $item->status == 1) { ?>
                                             <a class="label label-sm label-success" href="#">Validé</a>
                                                     <?php } ?>

                                            <?php endif;
                                         }

                                      endforeach; ?>
                                 </td>
                                <?php elseif($value) :

                                if(isset($col['clickable'])  && $col['clickable']== true):

                                    $params = array();

                                    if(isset($col['matching_params']) && !empty($col['matching_params']))
                                    {
                                        foreach($col['matching_params'] as $key){
                                            if(isset($item->$key))$params[$key] = $item->$key;
                                        }
                                    }
?>
                                    <td class="">
                                        <a href="<?php echo $this->url($col['route'], $params);?>">
                                            <?php echo $value ?>
                                        </a>
                                    </td>
                                <?php else:?>
                                    <td class="">
                                        <?php if($col['type'] == 'boolean'){

                                            if($value == 1){?>
                                                Oui
                                            <?php }else{?>
                                                Non
                                            <?php }
                                        }else{

                                            echo $value;
} ?>
                                    </td>
                                <?php endif; ?>

                                <?php else :  ?>
                                    <td class=""> <?php if($col['type'] == 'boolean'){
                                            if($value == 0){?>
                                               Non

                                            <?php }}
                                        else {?>
                                             N/A
                                        <?php }?>
                                        </td>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                    <?php endif; ?>
                </div>
                <div class="row">
                    <?php if($this->pagination_available):?>
                        <?php echo $this->paginator ?>
                    <?php endif;?>
                </div>
                <input id="export-csv" type="hidden" name="export-csv" value="0" />
                <input id="reset-filter" type="hidden" name="reset" value="0" />
</form>
        </div>
    </div>
</div>
<!-- End: life time stats -->
