<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title">Utilisation de l'outil de téléchargement d'images</h3>
    </div>
    <div class="panel-body">
        <p>Cet outil n'est pas lié au système d'enregistrement du lot, vous n'avez donc pas besoin de cliquer sur le bouton "Sauvegarder" pour ajouter les images. Autrement dit, le fait de ne pas sauvegarder n'annule pas les images précédemment ajoutées.</p>
        <p class="help-block">
        <ul>
            <li>Seuls les fichiers d'image (<strong>JPG, JPEG, GIF, PNG</strong>) sont autorisées.</li>
            <li>La taille maximale de fichier pour les images est de <strong>4 Mo</strong>.</li>
            <li>Pour les lots, les dimensions des images doivent avoir, au minimum, <strong>800px</strong> de largeur et <strong>600px</strong> de hauteur.</li>
        </ul>
    </div>
</div>