<footer>
    <div class="row" style="width: 80%;margin: auto;">
        <div class="img_footer_mobile"><img src="<?php echo $this->basePath() ?>/images/little_horse.png"/></div>
        <div class="col-md-3 footer-col footer-col-separator" style="min-height: 120px">
            <span style="font-family: Lato; font-weight:bold; font-size:12pt; color:#000000"><img class="img_footer_cache_mobile" src="<?php echo $this->basePath() ?>/images/little_horse.png"/>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->translate("EKESTRIAN", $this->lang_id); ?></span>
            <ul>
                <li class="letter-spacing-2" style="font-family: Lato-light; font-size:12pt; line-height: 17pt;color: #000000"><a href="http://www.ekestrian.com/conditions-generales"> <?php echo $this->translate("CGU", $this->lang_id); ?></a></li>
                <li class="letter-spacing-2" style="font-family: Lato-light; font-size:12pt; line-height: 17pt;color: #000000"><a href="http://www.ekestrian.com/mentions-legales"> <?php echo $this->translate("Mentions légales", $this->lang_id); ?></a></li>
            </ul>
        </div>
        <div class="col-md-3 footer-col footer-col-separator" style="min-height: 120px">
            <span style="font-family: Lato; font-weight:bold; font-size:12pt; color:#000000"><?php echo $this->translate("PLAN DU SITE"); ?></span>
            <ul>
                <li class="letter-spacing-2" style="font-family: Lato-light; font-size:12pt; line-height: 17pt;color: #000000"><a href="<?php echo $this->basePath() ?>#section-purchase"> <?php echo $this->translate("Concept", $this->lang_id); ?></a></li>
                <li class="letter-spacing-2" style="font-family: Lato-light; font-size:12pt; line-height: 17pt;color: #000000"><a href="<?php echo $this->basePath() ?>#section-selection"> <?php echo $this->translate("Nos services", $this->lang_id); ?></a></li>
                <li class="letter-spacing-2" style="font-family: Lato-light; font-size:12pt; line-height: 17pt;color: #000000"><a href="http://www.ekestrian.com/"> <?php echo $this->translate("Recherches"); ?></a></li>
                <li class="letter-spacing-2" style="font-family: Lato-light; font-size:12pt; line-height: 17pt;color: #000000"><a href="<?php echo $this->basePath() ?>#section-auction"> <?php echo $this->translate("Enchères", $this->lang_id); ?></a></li>
            </ul>
        </div>
        <div class="col-md-3 footer-col footer-col-separator" style="min-height: 120px">
            <span style="font-family: Lato;font-weight:bold;  font-size:12pt; color:#000000"><?php echo $this->translate("CONTACT"); ?></span>
            <ul>
                <li class="letter-spacing-2" style="font-family: Lato-light; font-size:12pt; line-height: 17pt;color: #000000"><a href="http://www.ekestrian.com"> <?php echo $this->translate("Ekestrian", $this->lang_id); ?></a></li>
                <li class="letter-spacing-2" style="font-family: Lato-light; font-size:12pt; line-height: 17pt;color: #000000"><a href="http://www.ekestrian.com/contact">+33 6 86 49 60 06</a></li>
                <li class="letter-spacing-2" style="font-family: Lato-light; font-size:12pt; line-height: 17pt;color: #000000"><a href="#">contact@ekestrian.com</a></li>
                <li class="letter-spacing-2" style="font-family: Lato-light; font-size:12pt; line-height: 17pt;color: #000000"><a href="http://www.ekestrian.com/contact"> <?php echo $this->translate("Une question ?", $this->lang_id); ?></a></li>
            </ul>
        </div>
        <div class="col-md-3 footer-col" style="min-height: 120px">
            <span class="letter-spacing-2" style="font-family: Lato-light; font-size:12pt; line-height: 17pt;color: #000000"> <?php echo $this->translate("SUIVEZ-NOUS, $this->lang_id"); ?></span>
            <p>
				<a href="https://www.facebook.com/Ekestrian" target="_blank"><img src="<?php echo $this->basePath() ?>/images/facebook.png" alt=""></a>
				<a href="https://www.instagram.com/ekestrian_/" target="_blank"><img src="<?php echo $this->basePath() ?>/images/inta.jpg" alt="" style="width: 17px"></a>
			</p>
        </div>
    </div>
</footer>
