<nav id="navbar-primary" class="navbar navbar-default" role="navigation" style="max-height: 120px;background: white;margin-bottom: 0px; padding-bottom: 40px;">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <div id="logo-mobile"><a href="http://www.ekestrian.com" class="menu-upper"><img id="logo-navbar-middle" src="<?php echo $this->basePath() ?>/images/logo@2x-01.png" width="150" alt="Ekestrian"></a></div>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-primary-collapse" aria-expanded="false">
                <span class="sr-only"><?php echo $this->translate("Toggle navigation", $this->lang_id); ?></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="navbar-primary-collapse">
            <ul class="nav navbar-nav">
                <li class="active separator-right"><a href="#section-purchase" class="menu-upper"><?php echo $this->translate("Le concept", $this->lang_id); ?></a></li>
                <li class="separator-right"><a href="#section-selection" class="menu-upper"><?php echo $this->translate("LE SERVICE", $this->lang_id); ?></a></li>
                <li id="ekestrian-menu-logo"><a href="http://www.ekestrian.com" class="menu-upper"><img id="logo-navbar-middle" src="<?php echo $this->basePath() ?>/images/logo@2x-01.png" width="150" alt="Ekestrian"></a></li>
                <li class="separator-left separator-right"><a href="http://www.ekestrian.com" class="menu-upper"><?php echo $this->translate("aller à ekestrian.com", $this->lang_id); ?></a></li>
                <li><a href="#section-auction" class="menu-upper"><img src="<?php echo $this->basePath() ?>/images/img_header.png" style="padding-right: 5px;padding-bottom: 2px;"/><?php echo $this->translate("Les ench&egrave;res", $this->lang_id); ?></a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav><!-- /.navbar -->