<div class="row" style="min-height: 30px;background: white; margin: 0">
    <div class="col-xs-12">
        <div style="padding: 0 2em;">
            <div style="float: right;line-height: 30px;padding: 0 30px; font-family: Lato-bold; font-size: 15px"><a href="<?php echo $this->url('home').(($this->lang_id == 1)?"en":""); ?>"><?php echo (($this->lang_id == 1)?"EN":"FR"); ?></a></div>
            <div style="float: right;line-height: 30px;">|</div>
            <?php if($this->is_membre_co == false) { ?>
            <div style="float: right;line-height: 30px;padding: 0 30px; font-family: Lato-bold; font-size: 15px"><a href="<?php echo $this->url('home/membre'); ?>"><?php echo $this->translate("Identification", $this->lang_id); ?></a></div>
            <?php } else { ?>
            
            <div style="float: right;line-height: 30px;padding: 0 30px; font-family: Lato-bold; font-size: 15px"><a href="<?php echo $this->url('home/membre/logout', array("membre_id" => $this->is_membre_co->client_id)); ?>"><?php echo $this->translate("Se déconnecter", $this->lang_id); ?></a></div>
            <div style="float: right;line-height: 30px;">|</div>
            <div style="float: right;line-height: 30px;padding: 0 30px; font-family: Lato-bold; font-size: 15px"><a href="<?php echo $this->url('home/membre/enchere', array("membre_id" => $this->is_membre_co->client_id)); ?>"><?php echo $this->translate("Mes enchères", $this->lang_id); ?></a></div>
            <div style="float: right;line-height: 30px;">|</div>
            <div style="float: right;line-height: 30px;padding: 0 30px; font-family: Lato-bold; font-size: 15px"><a href="<?php echo $this->url('home/membre/edit', array("membre_id" => $this->is_membre_co->client_id)); ?>"><?php echo $this->translate("Mon compte", $this->lang_id); ?></a></div>
            <div style="float: right;line-height: 30px;">|</div>
            <div style="float: right;line-height: 30px;padding: 0 30px; font-family: Lato-bold; font-size: 15px"><?php echo $this->translate("Bienvenue", $this->lang_id); ?> <?php echo $this->is_membre_co->lastname." ".$this->is_membre_co->firstname; ?></div>
            <?php } ?>
            <div style="clear:both"></div>
        </div>
    </div>
</div>

<nav id="navbar-primary" class="navbar navbar-default" role="navigation" style="max-height: 150px;background: white;margin-bottom: 0px; padding-bottom: 40px;border: 0px;">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <div id="logo-mobile"><a href="http://www.ekestrian.com" class="menu-upper"><img id="logo-navbar-middle" src="<?php echo $this->basePath() ?>/images/logo@2x-01.png" width="150" alt="Ekestrian"></a></div>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-primary-collapse" aria-expanded="false">
                <span class="sr-only"><?php echo $this->translate("Toggle navigation", $this->lang_id); ?></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="navbar-primary-collapse" style="border: 0px;">
            <ul class="nav navbar-nav">
                <li class="active separator-right"><a href="<?php echo $this->url('home'); ?>#section-purchase" class="menu-upper"><?php echo $this->translate("Le concept", $this->lang_id); ?></a></li>
                <li class="separator-right"><a href="<?php echo $this->url('home'); ?>#section-selection" class="menu-upper"><?php echo $this->translate("LE SERVICE", $this->lang_id); ?></a></li>
                <li id="ekestrian-menu-logo"><a href="http://www.ekestrian.com" class="menu-upper"><img id="logo-navbar-middle" src="<?php echo $this->basePath() ?>/images/logo@2x-01.png" width="150" alt="Ekestrian"></a></li>
                <li class="separator-left separator-right"><a href="<?php echo $this->url('home/partenaire'); ?>" class="menu-upper"><?php echo $this->translate("Partenaires", $this->lang_id); ?></a></li>
                <li><a href="<?php echo $this->url('home'); ?>#section-auction" class="menu-upper"><img src="<?php echo $this->basePath() ?>/images/img_header.png" style="padding-right: 5px;padding-bottom: 2px;"/><?php echo $this->translate("Les ench&egrave;res", $this->lang_id); ?></a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav><!-- /.navbar -->