
<section id="section-purchase" style="padding: 0px;">
    <div class="shell">
        <div class="section-inner" style="padding-top: 65px">
            <header class="section-head">
                <h2><?php echo $this->translate("LE CONCEPT DES VENTES", $this->lang_id); ?></h2>
            </header>
            <div class="section-body row" style="padding-bottom: 65px">
                <div class="col-md-3">
                    <img src="<?php echo $this->basePath() ?>/images/home/blason.png" alt="">
                    <img class="purchase-line" src="<?php echo $this->basePath() ?>/images/purchase-filet.png" alt="">
                    <p class="purchase-feature letter-spacing-2" style="font-family: Lato-light; font-size: 12pt; color: #242323;line-height: 17pt;color: white">
						<?php echo $this->translate("Vous cr&eacute;ez un compte et renseignez vos informations personnelles sur le formulaire sécuris&eacute;", $this->lang_id); ?>
                    </p>
                </div>
                <div class="col-md-3">
                    <img src="<?php echo $this->basePath() ?>/images/home/medaille.png" alt="">
                    <img class="purchase-line" src="<?php echo $this->basePath() ?>/images/purchase-filet.png" alt="">
                    <p class="purchase-feature letter-spacing-2" style="font-family: Lato-light; font-size: 12pt; color: #242323;line-height: 17pt;color: white">
                        <?php echo $this->translate("Vous ench&eacute;rissez et remportez une ench&egrave;re", $this->lang_id); ?>
                    </p>
                </div>
                <div class="col-md-3">
                    <img src="<?php echo $this->basePath() ?>/images/home/diplome.png" alt="">
                    <img class="purchase-line" src="<?php echo $this->basePath() ?>/images/purchase-filet.png" alt="">
                    <p class="purchase-feature letter-spacing-2" style="font-family: Lato-light; font-size: 12pt; color: #242323;line-height: 17pt;color: white">
                        <?php echo $this->translate("Vous signez le contrat de vente standardis&eacute;  et r&eacute;glez par virement bancaire sécuris&eacute; dans les 4h suivant l’achat", $this->lang_id); ?>
                    </p>
                </div>
                <div class="col-md-3">
                    <img src="<?php echo $this->basePath() ?>/images/home/camion.png" alt="">
                    <img class="purchase-line" src="<?php echo $this->basePath() ?>/images/purchase-filet.png" alt="">
                    <p class="purchase-feature letter-spacing-2" style="font-family: Lato-light; font-size: 12pt; color: #242323;line-height: 17pt;color: white">
                         <?php echo $this->translate("Ekestrian organise le transport (&agrave; vos frais) jusqu’&agrave; votre &eacute;curie Ou vous propose une pension d’&eacute;levage jusqu’&agrave; ses 3 ans", $this->lang_id); ?>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
