<section class="section" id="section-selection" style="margin: 0 50px; background: white;margin-top:30px;padding-bottom:60px">
    <div class="shell">
        <div class="section-head letter-spacing-10" style="margin: 0px; padding: 0px;">
            <h2><span><?php echo $this->translate("LES GARANTIES EKESTRIAN", $this->lang_id); ?></span></h2>
        </div>
        <div class="section-body section-body-ply row" style="margin: 0px; padding: 0px;">
            <div class="col-md-475" style="padding: 0px; text-align: left;">
                <img src="<?php echo $this->basePath() ?>/images/selection.png" alt="" style="width: 100%;margin: 0px;" />
            </div>
            <div class="col-md-03" style="width: 3%">&nbsp;</div>
            <div id="selection-features-wrapper" class="col-md-495" style="padding: 0px; margin:0px;">
                <div class="col-md-12 margin nopadding_r_l">
                    <div class="col-xs-12 margin nopadding_r_l">
                        <table style="width: 100%">
                            <tr>
                                <td class="check_text" style="vertical-align: top;text-align: right;"><img src="<?php echo $this->basePath() ?>/images/check.png" style="max-width: 20px; margin-right: 2em;" /></td>
                                <td class="text-check">
                                    <h3><div class="img_check_mobile"><img src="<?php echo $this->basePath() ?>/images/check.png" style="max-width: 20px; margin-right: 2em;" /></div><div class="label_check"><b><?php echo $this->translate("La solution la plus rigoureuse : un comit&eacute; d‘experts", $this->lang_id); ?></b></div></h3>
                                    <p class="txt-garanties"><?php echo $this->translate("Ekestrian vous propose une s&eacute;lection d’exception sur les critères d’origines et qualit&eacute; de la souche maternelle, raret&eacute;, modèle et allures. Le comit&eacute; de s&eacute;lection est constitu&eacute; d’experts en &eacute;levage qui ont prouv&eacute; leur savoir-faire par la qualit&eacute; de leur production et des choix qui les ont conduits à l’excellence.", $this->lang_id); ?></p>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="col-md-12 margin nopadding_r_l" style="margin-top: 40px;">
                    <div class="col-xs-12 margin nopadding_r_l">
                        <table style="width: 100%">
                            <tr>
                                <td class="check_text" style="vertical-align: top;text-align: right;"><img src="<?php echo $this->basePath() ?>/images/check.png" style="max-width: 20px; margin-right: 2em;" /></td>
                                <td class="text-check">
                                    <h3><div class="img_check_mobile"><img src="<?php echo $this->basePath() ?>/images/check.png" style="max-width: 20px; margin-right: 2em;" /></div><div class="label_check"><?php echo $this->translate("un achat en toute s&eacute;curit&eacute; : visite v&eacute;t&eacute;rinaire, contrat de vente, paiement s&eacute;curis&eacute;", $this->lang_id); ?></div></h3>
                                    <p class="txt-garanties"><?php echo $this->translate("Chaque foal est pr&eacute;sent&eacute; avec une visite v&eacute;t&eacute;rinaire de moins d’un mois publi&eacute;e sur la fiche du foal. Votre paiement en ligne est g&eacute;r&eacute; par Mangopay qui est un service de paiement s&eacute;curis&eacute; de la soci&eacute;t&eacute; Leetchi. Pour chaque foal le vendeur vous aura propos&eacute; un contrat sur le modèle de de Me Patrick de Chess&eacute;, avocat expert en droit &eacute;quin.", $this->lang_id); ?></p>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="section-body section-body-ply row" style="margin: 0px; padding: 0px;margin-top: 80px;">
            <div class="col-md-475 floatrightnotmobile" style="padding: 0px; text-align: left;">
                <img src="<?php echo $this->basePath() ?>/images/selection2.png" alt="" style="width: 100%;margin: 0px;" />
            </div>
            <div class="col-md-03 floatrightnotmobile" style="width: 3%">&nbsp;</div>
            <div id="selection-features-wrapper" class="col-md-495 floatrightnotmobile" style="padding: 0px; margin:0px">
                <div class="col-md-12 margin nopadding_r_l">
                    <div class="col-xs-12 margin nopadding_r_l">
                        <table style="width: 100%">
                            <tr>
                                <td class="check_text" style="vertical-align: top;text-align: right;"><img src="<?php echo $this->basePath() ?>/images/check.png" style="max-width: 20px; margin-right: 2em;" /></td>
                                <td class="text-check">
                                    <h3><div class="img_check_mobile"><img src="<?php echo $this->basePath() ?>/images/check.png" style="max-width: 20px; margin-right: 2em;" /></div><div class="label_check"><b><?php echo $this->translate("DES prix 100% transparents", $this->lang_id); ?></b></div></h3>
                                    <p class="txt-garanties"><?php echo $this->translate("Seulement 11% de frais de vente s’ajoutent au prix d’adjudication HT du foal. La TVA est en fonction de votre pays. Vous réglez le prix TTC", $this->lang_id); ?></p>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="col-md-12 margin nopadding_r_l" style="margin-top: 40px;">
                    <div class="col-xs-12 margin nopadding_r_l">
                        <table style="width: 100%">
                            <tr>
                                <td class="check_text" style="vertical-align: top;text-align: right;"><img src="<?php echo $this->basePath() ?>/images/check.png" style="max-width: 20px; margin-right: 2em;" /></td>
                                <td class="text-check">
                                    <h3><div class="img_check_mobile"><img src="<?php echo $this->basePath() ?>/images/check.png" style="max-width: 20px; margin-right: 2em;" /></div><div class="label_check"><?php echo $this->translate("service clef en main et personnalisé", $this->lang_id); ?></div></h3>
                                    <p class="txt-garanties"><?php echo $this->translate("Sur toute la durée des enchères, une hotline est mise à votre dispostion au +33 6 86 49 60 06. L'organisation du transport de votre poulain est organisée par Ekestrian, le transport reste à vos frais. Pour l'achat d'un poulain ou embryon, une offre d'assurance chez Hippcover facultative vous sera proposée. Ekestrian vous propose une pension d'élevage pour votre foal dans l'une des prestigieuses écuries partenaires jusqu'à ses 3 ans.", $this->lang_id); ?></p>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="section" id="section-comite" style="margin: 0 50px; background: white;margin-top:20px;padding-bottom:40px;margin-bottom: 40px;">
    <div class="shell">
        <div class="section-head" style="margin: 0px; padding: 0px;">
            <h2 class="letter-spacing-10"><span><?php echo $this->translate("NOTRE COMIT&eacute; DE S&eacute;LECTION", $this->lang_id); ?></span></h2>
        </div>
        <div class="section-body section-body-ply row" style="margin: 0px; padding: 0px;">
            <div class="col-md-3 margin" style="padding-top: 50px;">
                <div class="col-xs-12 margin"><img src="<?php echo $this->basePath() ?>/images/comite/olivier3.jpg" style="width: 80%; margin:auto"/></div>
                <div class="col-xs-12 margin">
                    <div class="nom-expert">Olivier Jouanneteau</div>
                    <div class="img-expert-ss-title" style="border-bottom: solid 1px #cecece;width: 40%;height: 1px;">&nbsp;</div>
                    <div class="description-expert">
                        <ul style="padding-left: 18px;text-align: justify">
                            <li style="color: #e76558"><span style="color:#585858"><?php echo $this->translate("Ex-grand cavalier international", $this->lang_id); ?></span></li>
                            <li style="color: #e76558"><span style="color:#585858"><?php echo $this->translate("Expert en élevage, propriétaire du Haras de Villers", $this->lang_id); ?></span></li>
                            <li style="color: #e76558"><span style="color:#585858"><?php echo $this->translate("Gagnant du Grand Prix Coupe du monde de Bordeaux en 2002 avec sa jument Ueleme", $this->lang_id); ?></span></li>
                            <li style="color: #e76558"><span style="color:#585858"><?php echo $this->translate("10 ans en équipe de France de Saut D'obstacles, gagant en coupe des nations", $this->lang_id); ?></span></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-3 margin" style="padding-top: 50px;">
                <div class="col-xs-12 margin"><img src="<?php echo $this->basePath() ?>/images/comite/xavier1.jpg" style="width: 80%; margin:auto"/></div>
                <div class="col-xs-12 margin">
                    <div class="nom-expert">Xavier Leredde</div>
                    <div class="img-expert-ss-title" style="border-bottom: solid 1px #cecece;width: 40%;height: 1px;">&nbsp;</div>
                    <div class="description-expert">
                        <ul style="padding-left: 18px;text-align: justify">
                            <li style="color: #e76558"><span style="color:#585858"><?php echo $this->translate("Ex-grand cavalier international", $this->lang_id); ?></span></li>
                            <li style="color: #e76558"><span style="color:#585858"><?php echo $this->translate("Expert en élevage, propriétaire du Haras des Rouges", $this->lang_id);?></span></li>
                            <li style="color: #e76558"><span style="color:#585858"><?php echo $this->translate("Réserviste aux JO de Barcelone en 1992", $this->lang_id);?></span></li>
                            <li style="color: #e76558"><span style="color:#585858"><?php echo $this->translate("Cavalier des célèbres Jalisco B et Papillon Rouge avec lesquels il gagne les championnats de France et le GP de Longchamp", $this->lang_id);?></span></li>
                            <li style="color: #e76558"><span style="color:#585858"><?php echo $this->translate("Sélectionneur et juge"); ?></span></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-3 margin" style="padding-top: 50px;">
                <div class="col-xs-12 margin"><img src="<?php echo $this->basePath() ?>/images/comite/Fabrice.jpg" style="width: 80%; margin:auto"/></div>
                <div class="col-xs-12 margin">
                    <div class="nom-expert">Fabrice Paris</div>
                    <div class="img-expert-ss-title" style="border-bottom: solid 1px #cecece;width: 40%;height: 1px;">&nbsp;</div>
                    <div class="description-expert">
                        <ul style="padding-left: 18px;text-align: justify">
                            <li style="color: #e76558"><span style="color:#585858"><?php echo $this->translate("Expert en élevage", $this->lang_id); ?> </span></li>
                            <li style="color: #e76558"><span style="color:#585858"><?php echo $this->translate("Propriétaire et Directeur du Haras des Forêts", $this->lang_id); ?></span></li>
                            <li style="color: #e76558"><span style="color:#585858"><?php echo $this->translate("Naisseur du célèbre Zirocco Blue (Alias Qamikase des Forêts), Rafale des Forêts et Ulysse des Forêts", $this->lang_id); ?></span></li>
                            <li style="color: #e76558"><span style="color:#585858"><?php echo $this->translate("Cavalier professionnel français", $this->lang_id); ?></span></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-3 margin" style="padding-top: 50px;">
                <div class="col-xs-12 margin"><img src="<?php echo $this->basePath() ?>/images/comite/patrick.jpg" style="width: 80%; margin:auto"/></div>
                <div class="col-xs-12 margin">
                    <div class="nom-expert">Patrick Clérin</div>
                    <div class="img-expert-ss-title" style="border-bottom: solid 1px #cecece;width: 40%;height: 1px;">&nbsp;</div>
                    <div class="description-expert">
                        <ul style="padding-left: 18px;text-align: justify">
                            <li style="color: #e76558"><span style="color:#585858"><?php echo $this->translate("Président de L'Association Des Éleveurs de Chevaux de Sport d'Ile de France", $this->lang_id); ?></span></li>
                            <li style="color: #e76558"><span style="color:#585858"><?php echo $this->translate("Ex-Sous Directeur du Haras National de Blois", $this->lang_id); ?></span></li>
                            <li style="color: #e76558"><span style="color:#585858"><?php echo $this->translate("Juge Selle Français aux USA et Canada", $this->lang_id); ?></span></li>
                            <li style="color: #e76558"><span style="color:#585858"><?php echo $this->translate("Juge National en France", $this->lang_id); ?></span></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
