<!--<section class="section" id="section-service" style="margin: 0 50px; background: white;margin-top:50px;padding-bottom:40px;margin-bottom: 40px;">
    <div class="shell">
        <div class="section-head"" style=";padding: 0px; margin: 0px">
			<h2 class="letter-spacing-10"><span>@Ekestrian.Language.Home.Resource.ServiceTitle</span></h2>
			 <div class="col-md-12 sous-titre">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore </div>
		</div>
        <div class="section-body">
            <div class="row">
                <div class="col-md-3">
                    <img src="@Url.Content("~/content/images/loupe.png")" alt="">
                    <img class="purchase-line" src="@Url.Content("~/content/images/purchase-filet.png")" alt="">
                    <div class="letter-spacing-2" style="text-transform: uppercase;font-family: Lato; font-size:14pt; color:#5c5c5c;line-height:18pt;margin-bottom: 15px;">Ench&egrave;re</div>
                    <p class="service-feature">
                        Vous enchérissez<br/> et remportez une<br/> enchère
                    </p>
                </div>
                <div class="col-md-3">
                    <img src="@Url.Content("~/content/images/medaille2.png")" alt="">
                    <img class="purchase-line" src="@Url.Content("~/content/images/purchase-filet.png")" alt="">
                    <div class="letter-spacing-2" style="text-transform: uppercase;font-family: Lato; font-size:14pt; color:#5c5c5c;line-height:18pt;margin-bottom: 15px;">Transport</div>
                    <p class="service-feature">
                        Ekestrian organise le transport (à vos frais) jusqu’à votre écurie Ou vous propose une pension d’élevage jusqu’à ses 3 ans
                    </p>
                </div>
                <div class="col-md-3">
                    <img src="@Url.Content("~/content/images/bouclier.png")" alt="">
                    <img class="purchase-line" src="@Url.Content("~/content/images/purchase-filet.png")" alt="">
                    <div class="letter-spacing-2" style="text-transform: uppercase;font-family: Lato; font-size:14pt; color:#5c5c5c;line-height:18pt;margin-bottom: 15px;">Securis&eacute;</div>
                    <p class="service-feature">
                        Vous créez un compte et renseignez vos informations personnelles sur le formulaire sécurisé 
                    </p>
                </div>
                <div class="col-md-3">
                    <img src="@Url.Content("~/content/images/cle.png")" alt="">
                    <img class="purchase-line" src="@Url.Content("~/content/images/purchase-filet.png")" alt="">
                    <div class="letter-spacing-2" style="text-transform: uppercase;font-family: Lato; font-size:14pt; color:#5c5c5c;line-height:18pt;margin-bottom: 15px;">Paiement</div>
                    <p class="service-feature">
                        Vous signez le contrat de vente standardisé  et réglez par virement bancaire sécurisé dans les 4h suivant l’achat
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
-->
<br/>
<br/>
<br/>
<br/>