<div class="main">
    <section id="section-concept" style="margin-top: 0px">
        <div class="shell">
            <div class="section-inner">
                <header class="section-head">
                    <!-- img src="<?php echo $this->basePath() ?>/images/section-concept-filet.png" alt="" id="concept-filet" -->
                </header>
            </div>
        </div>
    </section>
    
    <section class="section" id="section-auction" style="margin: 0 50px; background: white;margin-top: -30px; padding-bottom: 60px;">
        <div class="shell" style="max-width: 830px">
            <div class="section-head" style=";padding: 0px; margin: 0px">
                <h2 class="letter-spacing-10"><span><?php echo $this->translate("CONDITIONS GENERALES D'UTILISATION DU SITE ELITE AUCTION", $this->lang_id); ?></span></h2>
            </div>
            <div class="section-body section-body-ply row" style="padding: 0px; margin: 0 -15px">
                <div class="row">
                    <div class="col-xs-12">
                        <?php echo $this->translate("CGU_TEXT", $this->lang_id); ?>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>