
<section id="section-banner" style="margin-top: 0px;">
    <div class="shell">
        <div class="section-inner">
            <header class="section-head">
                <h2 class="menu-upper"><?php echo $this->translate($this->enchere->title,$this->lang_id); ?></h2>
                <img src="<?php echo $this->basePath() ?>/images/section-concept-filet.png" alt="" id="concept-filet">
            </header>
        </div>
    </div>
</section>

<section class="section" id="section-horse" style="margin: 0 50px; background: white;margin-top: -30px; padding-bottom: 60px">
    <div class="shell">
        <header class="section-head">
            <h2 ><span><?php echo  $this->translate($this->cheval->name,$this->lang_id)?></span></h2>
		<!-- @String.Concat("/Content/images/horse/",@Model.Horse.Name.ToString().ToUpper().Replace(" ", "_"), ".jpg") -->
            <div class="row margin">
                <div class="col-xs-12 main-info-horse" style="width: 400px; margin: auto;">
                    <div class="col-xs-12" style="text-align: center;padding:0px;margin:auto; ">
                        <div class="letter-spacing-2" style="float: left; font-family: Lato-bold;"><?php echo $this->translate("Foal", $this->lang_id); ?> : </div>
                        <div class="" style="float: left;"><?php echo $this->translate((($this->cheval->sex == "m")?"Mâle":(($this->cheval->sex == "f")?"Femelle":"Embryon")),$this->lang_id); ?></div>
                        <div style="float: left; width: 1px;border-right: solid 1px #a0a0a0;margin: 0 3px;line-height: 20.5pt;">&nbsp;</div>
                        <div class="letter-spacing-2" style="float: left; font-family: Lato-bold;"><?php echo $this->translate("Né le", $this->lang_id); ?> : </div>
                        <div class="" style="float: left;"><?php echo $this->cheval->birthday ?></div>
                    </div>
                </div>
            </div>
        </header>
    </div>
</section>
<section class="section" id="section-horses" style="margin: 0 50px; background: white;" >
    <?php if($this->lot->video_link != "") { ?>
        <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal" style="display: none"></button>

        <!-- Modal -->
        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title"></h4>
                    </div>
                    <div class="modal-body">
                        <?php echo $this->lot->video_link; ?>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate("Close", $this->lang_id); ?></button>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>

    <div class="shell2">
        <div class="section-body row" style="display: table">
            <div class="col-md-04 fiche_aff">&nbsp;</div>
            <div class="col-md-346 margin fiche_aff" style="vertical-align: middle">
                <div class="row" style="margin: 0px;">
                    <div class="col-md-144"  style="padding: 0px" id="slider-thumbs">
                        <!-- Bottom switcher of slider -->
                        <ul class="hide-bullets">
                            <?php /* 1er temps => image principal du lot*/ ?>
                            <?php
                            $i = 0;
                            if($this->lot->image_url != "" ){ ?>
                                <li class="col-sm-12" style="padding: 0px">
                                    <a href="<?php echo ((!empty($this->basePath()))?$this->basePath()."/":"").$this->lot->image_url; ?>" class="thumbnail" id="carousel-selector-0" data-gallery>
                                        <img src="<?php echo ((!empty($this->basePath()))?$this->basePath()."/":"").$this->lot->image_url; ?>" alt="" >
                                    </a>
                                </li>
                            <?php 
                                $i++;
                            } ?>
                            
                            <?php 
                            foreach ($this->lot->list_image as $image) { 
                                if( $i <= 4) {
                            ?>
                                    <li class="col-sm-12" style="padding: 0px">
                                        <a href="<?php echo $image; ?>" class="thumbnail" id="carousel-selector-<?php echo $i; ?>" data-gallery>
                                            <img src="<?php echo $image; ?>" alt="">
                                        </a>
                                    </li>
                            <?php  
                                    $i++;
                                } else {
                            ?>
                                    <li class="col-sm-12" style="padding: 0px; display: none">
                                        <a href="<?php echo $image; ?>" class="thumbnail" id="carousel-selector-<?php echo $i; ?>" data-gallery>
                                            <?php /*!--img src="<?php echo $image; ?>" alt="" -- */ ?>
                                        </a>
                                    </li>
                            <?php 
                                    $i++;
                                }
                            }
                            ?>
                        </ul>
                    </div>
                    <div class="col-md-855" style="padding: 0px">
                        <div class="col-xs-12" id="slider">
                            <!-- Top part of the slider -->
                            <div class="row">
                                <div class="col-sm-12" id="carousel-bounding-box">
                                    <div class="carousel slide" id="carousel-horse">
                                        <!-- Carousel items -->
                                        <div class="carousel-inner">
                                            <div class="item active" data-slide-number="1" data-src="<?php echo ((!empty($this->basePath()))?$this->basePath()."/":"").$this->lot->image_url; ?>">
                                                <img src="<?php echo ((!empty($this->basePath()))?$this->basePath()."/":"").$this->lot->image_url; ?>" alt="" style="width: 100%;">
                                            </div>
                                        </div>
										<!-- div class="carousel-inner">
											<div class="item active" data-slide-number="1" data-src="@String.Concat("/Content/images/horse/",@Model.Horse.Name.ToString().ToUpper().Replace(" ", "_"), ".jpg")">
												<img src="@String.Concat("/Content/images/horse/",@Model.Horse.Name.ToString().ToUpper().Replace(" ", "_"), ".jpg")" alt="" style="width: 100%;">
											</div>
										</div -->
                                        <div class="video_behind" style="display: none"><img src="<?php echo $this->basePath() ?>/images/picto_video.png" style="width:50%"/></div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                    <!--/Slider-->
                </div>
            </div>
            <div class="col-md-445 mobilehidden arbo_fiche" style="float: none">
                <table class="family-tree" width="100%" border="0">
                    <tbody>
                        <tr>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td class="tree-bottom">
                                <?php if($this->cheval->pere_pere_pere && is_object($this->cheval->pere_pere_pere)){ echo $this->translate($this->cheval->pere_pere_pere->name, $this->lang_id) ;}?>
                            </td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td class="tree-bottom">
                                <?php if($this->cheval->pere_pere && is_object($this->cheval->pere_pere)){ echo $this->translate($this->cheval->pere_pere->name, $this->lang_id) ;}?>
                            </td>
                            <td class="tree-left">&nbsp;</td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td class="tree-left">&nbsp;</td>
                            <td class="tree-bottom tree-left">
                                <?php if($this->cheval->mere_pere_pere && is_object($this->cheval->mere_pere_pere)){ echo $this->translate($this->cheval->mere_pere_pere->name, $this->lang_id) ;}?>
                            </td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td class="tree-bottom">
                                <?php if($this->cheval->pere && is_object($this->cheval->pere)){ echo $this->translate($this->cheval->pere->name, $this->lang_id) ;}?>
                            </td>
                            <td class="tree-left">&nbsp;</td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td class="tree-left">&nbsp;</td>
                            <td class="tree-left">&nbsp;</td>
                            <td class="tree-bottom">
                                <?php if($this->cheval->pere_mere_pere && is_object($this->cheval->pere_mere_pere)){ echo $this->translate($this->cheval->pere_mere_pere->name, $this->lang_id) ;}?>
                            </td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td class="tree-left">&nbsp;</td>
                            <td class="tree-bottom tree-left">
                                <?php if($this->cheval->mere_pere && is_object($this->cheval->mere_pere)){ echo $this->translate($this->cheval->mere_pere->name, $this->lang_id) ;}?>
                            </td>
                            <td class="tree-left">&nbsp;</td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td class="tree-left">&nbsp;</td>
                            <td>&nbsp;</td>
                            <td class="tree-left tree-bottom">
                                <?php if($this->cheval->mere_mere_pere && is_object($this->cheval->mere_mere_pere)){ echo $this->translate($this->cheval->mere_mere_pere->name, $this->lang_id) ;}?>
                            </td>
                        </tr>
                        <tr>
                            <td class="family-separator tree-bottom">&nbsp;</td>
                            <td class="family-separator tree-left">&nbsp;</td>
                            <td class="family-separator">&nbsp;</td>
                            <td class="family-separator">&nbsp;</td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td class="tree-left">&nbsp;</td>
                            <td>&nbsp;</td>
                            <td class="tree-bottom">
                                <?php if($this->cheval->pere_pere_mere && is_object($this->cheval->pere_pere_mere)){ echo $this->translate($this->cheval->pere_pere_mere->name, $this->lang_id) ;}?>
                            </td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td class="tree-left">&nbsp;</td>
                            <td class="tree-bottom">
                                <?php if($this->cheval->pere_mere && is_object($this->cheval->pere_mere)){ echo $this->translate($this->cheval->pere_mere->name, $this->lang_id) ;}?>
                            </td>
                            <td class="tree-left">&nbsp;</td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td class="tree-left">&nbsp;</td>
                            <td class="tree-left">&nbsp;</td>
                            <td class="tree-bottom tree-left">
                                <?php if($this->cheval->mere_pere_mere && is_object($this->cheval->mere_pere_mere)){ echo $this->translate($this->cheval->mere_pere_mere->name, $this->lang_id) ;}?>
                            </td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td class="tree-bottom tree-left">
                                <?php if($this->cheval->mere && is_object($this->cheval->mere)){ echo $this->translate($this->cheval->mere->name, $this->lang_id) ;}?>
                            </td>
                            <td class="tree-left">&nbsp;</td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td class="tree-left">&nbsp;</td>
                            <td class="tree-bottom">
                                <?php if($this->cheval->pere_mere_mere && is_object($this->cheval->pere_mere_mere)){ echo $this->translate($this->cheval->pere_mere_mere->name, $this->lang_id) ;}?>
                            </td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td class="tree-bottom tree-left">
                                <?php if($this->cheval->mere_mere && is_object($this->cheval->mere_mere)){ echo $this->translate($this->cheval->mere_mere->name, $this->lang_id) ;}?>
                            </td>
                            <td class="tree-left">&nbsp;</td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td class="tree-bottom tree-left">
                                <?php if($this->cheval->mere_mere_mere && is_object($this->cheval->mere_mere_mere)){ echo $this->translate($this->cheval->mere_mere_mere->name, $this->lang_id);}?>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            
            <div class="col-md-166 margin fiche_aff" style="text-align: center;margin-top: 13%;">
                <?php if($this->can_enchere == true) { ?>
                    <div class="price col-xs-12 margin"  style="font-family: Lato-bold; font-weight:regular; font-size:20pt; line-height: 21pt;color:#e76558">
                        <span class="letter-spacing-1" style="font-family: Lato-bold; font-weight:bold;font-size:15pt;line-height:26pt; color: #e97266"><?php echo $this->translate("Enchère actuelle", $this->lang_id); ?> </span>
                    </div>
                    <div class="price col-xs-12 margin"  style="font-family: Lato-bold; font-weight:regular; font-size:20pt; line-height: 21pt;color:#e76558; margin-bottom: 15px">
                        <span class="actual_amount_space"><?php echo $this->lot->actual_cost; ?></span> <span>€</span> <sup>HT</sup>
                    </div>
                    <?php if($this->is_membre_co == false) { ?>
                        <a href="<?php echo $this->url('home/membre', array('lang'=>$this->lang_id)); ?>" ><div class="btn btn-ekestrian-fill" style="margin-bottom: 20px;"><?php echo $this->translate("Enchérir", $this->lang_id); ?></div></a>
                    <?php } else { ?>
                        <a href="#" id="lien_enchere" ><div class="btn btn-ekestrian-fill" style="margin-bottom: 20px;"><?php echo $this->translate("Enchérir", $this->lang_id); ?></div></a>
                    <?php } ?>
                <?php } ?>
            </div>
       </div>
    </div>
</section>

<?php if($this->can_enchere == true) { ?>
<div class="dialog_enchere">
    <div class="row" style="margin: 0">
        <div class="col-xs-12 actual_amount" style="text-align:center"></div>
        <br/>
        <div class="col-xs-12 success" style="text-align:center; color: green"></div>
        <div class="col-xs-12 alerte" style="text-align:center; color: red"></div>
        <br/>
        <div class="col-xs-12 enchere" style="text-align:center;">
            <div class="col-xs-10 enchere" style="text-align:center;float: none; margin: auto; border: solid 1px black">
                <div class="col-xs-12"style="z-index: 1001;background: white;margin-top: -10px;margin-bottom: 20px;"><?php echo $this->translate("PLACER UNE ENCH&Egrave;RE", $this->lang_id); ?></div>
                <div class="row" style="padding-bottom: 10px;">
                    <div class="col-xs-12">
                        <div class="col-xs-5" style="padding: 0px;">
                            <select name="amount" style="height: 24px;"></select>
                        </div>
                        <div class="col-xs-2" style="padding: 0px;line-height: 24px;">EUR</div>
                        <div class="col-xs-5" style="padding: 0px">
                            <input type="button" value="ENCH&Egrave;RIR" style="background: transparent;border: solid 1px black;padding: 2px;"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="dialog_validation_enchere">
    <div class="row" style="margin: 0">
        <div class="col-xs-12 content" style="text-align:center"></div>
    </div>
</div>
<?php } ?>
<?php if ($this->cheval->pere != null) { ?>
    <section class="section" id="section-auction" style="margin: 0 50px; background: white;margin-top:20px;padding-bottom:50px">
        <div class="shell">
            <header class="section-head" style=";padding: 0px; margin: 0px"><h2><span><?php echo $this->translate("DESCRIPTION DU PÈRE", $this->lang_id); ?></span></h2></header>
            <div class="section-body row">
                <div class="col-xs-12" style="">
                    <h3 style="font-family: Lato;font-size:16pt;line-height:17pt; color: #585858;margin-top: 50px;"><?php echo $this->translate($this->cheval->pere->name, $this->lang_id); ?></h3>
                        
                    <div class="row" style="margin-bottom: 20px;">
                        <div class="col-md-12">
                            <div style=" width: 25%; margin-bottom:15px">
                                <img class="lot-filet" src="<?php echo $this->basePath() ?>/images/lot/lot-filet.png" alt="">
                            </div>
                        </div>
                        <div class="col-md-12 letter-spacing-1 horse-description" style=""><?php echo (($this->lang_id == 'fr')?$this->cheval->pere->description:$this->cheval->pere->description_en); ?></div>
                    </div>

                </div>
            </div>
        </div>
    </section>
<?php 
}

if ($this->cheval->mere != null) { ?>
    <section id="section-mother" class="section" style="margin: 0 50px; background: white;padding-bottom:40px; position: relative">
        <div class="shell">
            <header class="secition-head">
                <h2><span><?php echo $this->translate("DESCRIPTION DES MÈRES", $this->lang_id); ?></span></h2>
            </header>
            <div class="section-body section-body-ply row" style="padding: 0px">
                <div class="col-md-12" style="margin-top: 65px">
                    <div class="col-xs-12 margin">
                        <h3 style="font-family: Lato; font-weight:regular;font-size:20pt;line-height:18pt; color: black"><?php echo $this->translate("1<sup>ère</sup> Mère", $this->lang_id); ?></h3>
                        <img class="horse-filet" src="<?php echo $this->basePath() ?>/images/horse/horse-filet.png" alt="">
                        <h4 class="letter-spacing-1" style="margin-bottom: 20px;font-family: Lato;font-size:15pt;line-height:22pt; color: #e76558"><?php echo $this->translate($this->cheval->mere->name, $this->lang_id); ?></h4>
                        <p style="margin-bottom: 30px">
                            <span class="letter-spacing-1 horse-description">
                                <?php echo (($this->lang_id == 'fr')?$this->cheval->mere->description:$this->cheval->mere->description_en); ?>
                            </span>
                        </p>
                    </div>
                </div>

                <?php if (property_exists($this->cheval, "mere_mere") && $this->cheval->mere_mere != null) { ?>
                    <div class="col-md-12" style="margin-top: 65px">
                        <div class="col-xs-12 margin">
                            <h3 style="font-family: Lato; font-weight:regular;font-size:20pt;line-height:18pt; color: black"><?php echo $this->translate("2<sup>ème</sup> Mère", $this->lang_id); ?></h3>
                            <img class="horse-filet" src="<?php echo $this->basePath() ?>/images/horse/horse-filet.png" alt="">
                            <h4 class="letter-spacing-1" style="margin-bottom: 20px;font-family: Lato; font-size:15pt;line-height:22pt; color: #e76558"><?php echo $this->translate($this->cheval->mere_mere->name, $this->lang_id); ?></h4>
                            <p style="margin-bottom: 30px">
                                <span class="letter-spacing-1 horse-description">
                                    <?php echo (($this->lang_id == 'fr')?$this->cheval->mere_mere->description:$this->cheval->mere_mere->description_en) ?>
                                </span>
                            </p>
                        </div>
                    </div>

                <?php 
                }
                
                if (property_exists($this->cheval, "mere_mere_mere") && $this->cheval->mere_mere_mere != null) { 
                ?>
                    <div class="col-md-12" style="margin-top: 65px">
                        <div class="col-xs-12 margin">
                            <h3 style="font-family: Lato; font-weight:regular;font-size:20pt;line-height:18pt; color: black"><?php echo $this->translate("3<sup>ème</sup> Mère", $this->lang_id); ?></h3>
                            <img class="horse-filet" src="<?php echo $this->basePath() ?>/images/horse/horse-filet.png" alt="">
                            <h4 class="letter-spacing-1" style="margin-bottom: 20px;font-family: Lato;font-size:15pt;line-height:22pt; color: #e76558"><?php echo $this->translate($this->cheval->mere_mere_mere->name, $this->lang_id); ?></h4>
                            <p style="margin-bottom: 30px">
                                <span class="letter-spacing-1 horse-description">
                                    <?php echo (($this->lang_id == 'fr')?$this->cheval->mere_mere_mere->description:$this->cheval->mere_mere_mere->description_en); ?>
                                </span>
                            </p>
                        </div>
                    </div>

                <?php 
                }
                
                if (property_exists($this->cheval, "mere_mere_mere_mere") && $this->cheval->mere_mere_mere_mere != null) { 
                ?>
                    <div class="col-md-12" style="margin-top: 65px">
                        <div class="col-xs-12 margin">
                            <h3 style="font-family: Lato; font-weight:regular;font-size:20pt;line-height:18pt; color: black"><?php echo $this->translate("4<sup>ème</sup> Mère", $this->lang_id); ?></h3>
                            <img class="horse-filet" src="<?php echo $this->basePath() ?>/images/horse/horse-filet.png" alt="">
                            <h4 class="letter-spacing-1" style="margin-bottom: 20px;font-family: Lato;font-size:15pt;line-height:22pt; color: #e76558"><?php echo $this->translate($this->cheval->mere_mere_mere_mere->name, $this->lang_id); ?></h4>
                            <p style="margin-bottom: 30px">
                                <span class="letter-spacing-1 horse-description">
                                    <?php echo (($this->lang_id == 'fr')?$this->cheval->mere_mere_mere_mere->description:$this->cheval->mere_mere_mere_mere->description_en); ?>
                                </span>
                            </p>
                        </div>
                    </div>
                <?php } ?>
            </div>
        </div>
        <div style="width: 100%; bottom: -30px; position: absolute; text-align: center">
            <img src="<?php echo $this->basePath() ?>/images/bloc_bottom_img.png" />
        </div>            
    </section>
<?php } ?>

<!-- section class="section" id="section-other-lots" style="margin: 0 50px; margin-top: 50px; background: white;">
    <div class="shell">
        <header class="section-head" style=";padding: 0px; margin: 0px">
            <h2><span>DÉCOUVREZ NOS AUTRES VENTES
</span></h2>
        </header>
        <div class="section-body section-body-ply col-md-12" style="padding: 0px;margin-top: 70px; padding-bottom: 60px">
            <div class="row">
                <div class="col-xs-12">
                    <div class="col-md-5-5" style="padding: 0px; position: relative">
                        <div style="font-family: Raleway;font-size: 20pt;color: white;position: absolute; left: 31%; top: 40%; border-bottom: solid 1px white; padding-bottom: 20px"><a href="#">ENCH&Egrave;RE X</a></div>
                        <img src="/Content/images/horse_1.png" style="width:100%;max-height: 368px" />
                    </div>
                    <div class="col-md-0-5" style="padding: 0px">&nbsp;</div>
                    <div class="col-md-5-5" style="padding: 0px; position: relative">
                        <div style="font-family: Raleway;font-size: 20pt;color: white;position: absolute; left: 31%; top: 40%; border-bottom: solid 1px white; padding-bottom: 20px"><a href="#">ENCH&Egrave;RE Y</a></div>
                        <img src="/Content/images/horse_2.png" style="width:100%;max-height: 368px"/>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section -->

<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <div class="modal fade">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-primary next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
        

<script type="text/javascript">
    <?php if($this->can_enchere == true) { ?>
    function reloadAmount() {
        $.ajax({
            url: '<?= $this->url("home/lots/lot/reload_cost", array("enchere_id"=>$this->enchere_id, "lot_id"=>$this->lot_id)) ?>',
            dataType: 'json',
            data: {},
        }).always(function () {
        }).done(function (result) {
            setTimeout(reloadAmount, 3000);
            if(result.status && result.status == 1 && result.data && result.data.amount) {
                $('.actual_amount_space').empty().html(result.data.amount);
            }
        });
    }
    <?php } ?>
    
    $(document).ready(function(){
        <?php if($this->can_enchere == true) { ?>reloadAmount();<?php } ?>
        $('#slider-thumbs li a').unbind('click').on('click', function(e){
            e.preventDefault();
            $('#blueimp-gallery').data('fullScreen', true);
            $('#blueimp-gallery').data('hidePageScrollbars', false);
            blueimp.Gallery($('#slider-thumbs a'), $('#blueimp-gallery').data());
        });

        if($( 'button[data-toggle="modal"]' ).length != 0) {
            $('.carousel-inner > div, .video_behind').unbind('click').on('click', function(e){
                e.preventDefault();
                $( 'button[data-toggle="modal"]' ).trigger("click");
            });


            /*$('.carousel-inner > div').unbind('mouseover').on('mouseover', function(e){*/
                $('.carousel-inner > div').attr('style', "background-color: black; opacity: 0.5; z-index: 1001");
                $('.video_behind').show();
            /*});
            $('.carousel-inner > div').unbind('mouseout').on('mouseout', function(e){
                $('.carousel-inner > div').attr('style', "");
                $('.video_behind').hide();
            });*/
            $('#carousel-bounding-box').unbind('click').on('click', function(e){
                e.preventDefault();
            });
            $('.carousel-inner').unbind('click').on('click', function(e){
                e.preventDefault();
            });
        }
        
        <?php if($this->can_enchere == true) { ?>
            $('.dialog_enchere').dialog({
                autoOpen: false,
                minWidth: 500,
                minHeight: 310
            });

            $('.dialog_validation_enchere').dialog({
                autoOpen: false,
                minWidth: 500,
                minHeight: 310
            });
        
            $('.dialog_enchere input[type="button"]').unbind('click').on('click', function(e){
               e.preventDefault();
                $.ajax({
                    url: '<?= $this->url("home/lots/lot/validation", array("enchere_id"=>$this->enchere_id, "lot_id"=>$this->lot_id)) ?>',
                    dataType: 'json',
                    data: {"value":$('.dialog_enchere select').val()},
                }).always(function () {
                }).done(function (result) {
                    if(result.status && result.status == 1) {
                        /*$('.dialog_enchere .alerte').empty();
                        $(".dialog_enchere select option").remove();
                        $('.dialog_enchere .success').empty().html("<?php echo $this->translate("Enchère enregistrée, un mail de confirmation vient de vous être envoyé", $this->lang_id); ?>");
                        /* mise en place de actual_amount *\/
                        var actuel = parseFloat((result.data.auction)?result.data.auction.value:result.data.lot.min_price);
                        $('.dialog_enchere .actual_amount').empty().html("<?php echo $this->translate('Enchère actuelle', $this->lang_id); ?> : "+actuel+" EUR");

                        if(actuel <= result.data.lot.reserve_price){
                            $('.dialog_enchere .alerte').empty().html("<?php echo $this->translate('Prix de reserve atteint', $this->lang_id); ?>");
                        }   

                        var pas = parseFloat((result.data.lot.ist_price && result.data.lot.ist_price > 0)?result.data.lot.ist_price : 1);
                        var i = 1;
                        while(i != 10) {
                            actuel = actuel + pas;
                            $(".dialog_enchere select").append('<option value="'+(actuel)+'">'+(actuel)+'</option>');
                            i++;
                        }*/
                        $('.dialog_enchere').dialog('close');
                        $('.dialog_validation_enchere .content').empty().html("<?php echo $this->translate("Enchère enregistrée, un mail de confirmation vient de vous être envoyé à l'adresse : ", $this->lang_id); ?>"+result.data.email);
                        $('.dialog_validation_enchere').dialog('open');
                        setTimeout(function(){ $('.dialog_validation_enchere').dialog('close'); }, 10000);
                    } else {
                        $('.dialog_enchere .alerte').empty().html(result.data);
                    }
                });
            });
        <?php } ?>
    });
    
    /* Mise en place de l'enchère */
    <?php if($this->can_enchere == true) { ?>
        $('#lien_enchere').unbind('click').on('click', function(e){
            e.preventDefault();
            $.ajax({
                url: '<?= $this->url("home/lots/lot/information", array("enchere_id"=>$this->enchere_id, "lot_id"=>$this->lot_id)) ?>',
                dataType: 'json',
                context: $(this)[0]
            }).always(function () {
            }).done(function (result) {
                if(result.status && result.status == 1) {
                    /* mise en place de actual_amount */
                    var actuel = parseFloat((result.data.auction)?result.data.auction.value:result.data.lot.min_price);
                    $('.dialog_enchere .actual_amount').empty().html("<?php echo $this->translate('Enchère actuelle', $this->lang_id); ?> : "+actuel+" EUR");

                    if(actuel <= result.data.lot.reserve_price){
                        $('.dialog_enchere .alerte').empty().html("<?php echo $this->translate('Prix de reserve atteint', $this->lang_id); ?>");
                    }   

                    var pas = parseFloat((result.data.lot.ist_price && result.data.lot.ist_price > 0)?result.data.lot.ist_price : 1);
                    var i = 1;
                    while(i != 10) {
                        actuel = actuel + pas;
                        $(".dialog_enchere select").append('<option value="'+(actuel)+'">'+(actuel)+'</option>');
                        i++;
                    }
                    $('.dialog_enchere').dialog('open');
                } else {
                    alert(result.data);
                }
            });
        });
    <?php } ?>
    /*} else {
        $(document).ready(function(){
            //$('.carousel-inner').lightGallery({
            //    selector: '.item',
            //    autoplay : 'false',
            //    videojs: true
            //});
            $('.carousel-inner').lightGallery(
                {
                    loadYoutubeThumbnail: true,
                    youtubeThumbSize: 'default',
                    selector: '.item',
                    youtubePlayerParams: {
                        modestbranding: 1,
                        showinfo: 0,
                        rel: 0,
                        controls: 0
                    },
                }
           );
        });
    }*/
</script>
