<section id="section-banner" style="margin-top: 0px;">
    <div class="shell">
        <div class="section-inner">
            <header class="section-head">
                <h2 class="letter-spacing-10" style="margin-bottom: 35px;font-family: Lato; font-size: 23pt; line-height: 18pt; color: #dbdbd9;"><?php echo $this->translate((($this->enchere)?$this->enchere->title:""), $this->lang_id); ?></h2>
                <img src="<?php echo $this->basePath() ?>/images/section-concept-filet.png" alt="" id="concept-filet">
            </header>
        </div>
    </div>
</section>

<section class="section" id="section-summary" style="margin: 0 50px; background: white;margin-top: -30px">
    <div class="shell">
        <header class="section-head" style=";padding: 0px; margin: 0px">
            <h2><span><?php echo $this->translate("Nos lots", $this->lang_id);?></span></h2>
            <h3 class="section-summary-soustitre"><?php echo $this->translate("Il y a", $this->lang_id)." ".count($this->lots)." ".$this->translate("lots dans cette enchère", $this->lang_id); ?></h3>
			<!--<div class="col-md-12 sous-titre"> @Model.Description</div>-->
			<div class="col-md-12 sous-titre"><?php echo $this->translate("Première vente aux enchères en ligne de foals de CSO d'exception.<br/>Ouverture des ventes le 26 Octobre 2016, possibilité d'enchérir à partir du 30 Octobre à 20h00, fin des enchères le 2 Novembre à 20h00.", $this->lang_id); ?></div>
        </header>
        <div class="row recherche_lots">
            <div class="col-xs-12" style="height:1px; border-top: solid 1px #ececec; margin-bottom: 15px;font-family: Lato;font-size: 18pt;">&nbsp;</div>
                <div class="row">
                    <div class="col-xs-12 margin">
                        <div class="col-xs-12 margin">
                            <div class="col-md-18">&nbsp;</div>
                            <div class="col-md-215" style="padding-left: 0px">
                                <a href="#"><div class="col-md-10" style="color:#e76558; border: solid 1px #e76558; line-height: 30px;font-family: Lato;font-size: 18pt;text-align: center;"><?php echo $this->translate("Tous", $this->lang_id); ?></div></a>
                            </div>
                            <div class="col-md-110" style="padding-left: 0px;font-family: Lato;font-size: 18pt;"><a href="#"><?php echo $this->translate("Père", $this->lang_id); ?></a></div>
                            <div class="col-md-125" style="padding-left: 0px;font-family: Lato;font-size: 18pt;"><a href="#"><?php echo $this->translate("Mère", $this->lang_id); ?></a></div>
                            <div class="col-md-176" style="padding-left: 0px;font-family: Lato;font-size: 18pt;"><a href="#"><?php echo $this->translate("Père de Mère", $this->lang_id); ?></a></div>
                            <div class="col-md-19" style="padding-left: 0px;">
                                <div class="" style="width: 140px;position: relative">
                                    <input type="text" id="search" style="border: none;border-bottom: solid 1px;width: 100%"/>
                                    <img src="<?php echo $this->basePath() ?>/images/icon_search.png" style="position: absolute;top: 0;right: 0px;"/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <div class="col-xs-12" style="height:1px; border-top: solid 1px #ececec; margin-top: 15px; margin-bottom: 40px;">&nbsp;</div>
        </div>
    </div>
</section>

<section class="section" id="section-lots" style="margin: 0 50px; background: white;">
    <div class="shell">
        <?php foreach($this->lots as $lot) { ?>
            <div class="section-body row lot-row">
                <div class="col-xs-12 margin">
                    <div class="col-md-3 ux-hover margin">
                        <div class="img-wrapper">
                            <a href="<?php echo $this->url("home/lots/lot", array("enchere_id" => $lot->enchere_id, "lot_id" => $lot->lot_id, 'lang'=>$this->lang_id)); ?>">
                                <!-- img src="@lot.Image" alt="" class="zoom" -->
                                <img src="<?php echo $this->basePath().$lot->image_url; ?>" alt="Photo non trouv&eacute;e" onerror="imgError(this)" class="zoom">
                            </a>
                        </div>
                    </div>
                    <div  class="col-md-05"> &nbsp</div>
                    <div class="col-md-456 coll-offset-2 margin">
                        <div class="row">
                            <div class="col-md-12">
                                <h3 class="col-xs-12 letter-spacing-5 auction-name"><?php echo $lot->title; ?></h3>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="col-xs-12">
                                    <img class="lot-filet" src="<?php echo $this->basePath() ?>/images/lot/lot-filet.png" alt="">
                                </div>
                            </div>
                            <div class="col-md-6" style="padding: 0px; margin-top: 20px;">
                                &nbsp;
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="col-xs-12 letter-spacing-2">
                                <?php if ($lot->pere && $lot->pere != null) {?>
                                    <div class="lot-features"><span><?php echo $this->translate("Père", $this->lang_id); ?> : </span><?php echo $lot->pere->name; ?></div>
                                <?php } if ($lot->mere && $lot->mere != null) { ?>
                                    <div class="lot-features"><span><?php echo $this->translate("Mère", $this->lang_id); ?> : </span><?php echo $lot->mere->name; ?></div>
                                <?php } if ($lot->pere_mere && $lot->pere_mere != null) { ?>
                                    <div class="lot-features last"><span><?php echo $this->translate("Père de mère", $this->lang_id); ?> : </span><?php echo $lot->pere_mere->name; ?></div>
                                <?php } ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-24 coll-offset-2 margin">
                        <div class="row">
                            <div class="col-md-12">
                                <!--<div class="price col-xs-12 margin"  style="font-family: Lato;  font-size:16pt; color:#000000; line-height:18.31pt">
                                    <span>@Ekestrian.Language.Lots.Resource.EstimatedPrice </span>15000
                                    <span>€</span> <sup>@Ekestrian.Language.Lots.Resource.HT</sup>
                                </div>-->
                            </div>
                        </div>
                        
                        <div class="row" style="margin-top: 46px;">
                            <div class="col-md-12">
                                <div class="col-xs-12 margin lot-sale-container">
                                    <!-- div class="auction-current" style="font-family: Lato; font-weight:regular; font-size:14pt; color:#e76558; line-height: 18pt"> 
                                        @Ekestrian.Language.Lots.Resource.ActualAuctionLabel<br>
                                        <span>
                                            <span style="font-family: Lato-bold; font-weight:bold; font-size:18pt; color:#e76558; line-height: 18.31pt">- €</span>
                                            <sup>@Ekestrian.Language.Lots.Resource.HT</sup>
                                        </span>
                                    </div>
                                    <div class="time"> @lot.RemainingTime </div -->
                                    <!--<div class="btn-container" style="margin-top: 15px">
                                        <a href="@Url.Action("lot","auction",new { id = lot.Id })">
                                            <div class="mb5 btn btn-ekestrian-fill" style="font-family: Lato; font-weight:regular; font-size:12pt; color:white">
                                                @Ekestrian.Language.Lots.Resource.BidLinkText
                                            </div>
                                        </a>
                                    </div>-->
                                    <div class="btn-container">
                                        <div class="btn-ekestrian-alt">
                                            <a href="<?php echo $this->url("home/lots/lot", array("enchere_id" => $lot->enchere_id, "lot_id" => $lot->lot_id, 'lang'=>$this->lang_id)); ?>" style="font-family: Lato; font-weight:normal;font-style: normal; font-size:12pt; color:#e76558">
                                                <?php echo $this->translate("Voir ce lot", $this->lang_id); ?>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
</section>

<!-- section class="section" id="section-other-lots" style="margin: 0 50px; margin-top: 25px; background: white;">
    <div class="shell">
        <header class="section-head" style=";padding: 0px; margin: 0px">
            <h2><span>D&eacute;COUVREZ NOS AUTRES VENTES
</span></h2>
        </header>
        <div class="section-body section-body-ply col-md-12" style="padding: 0px;margin-top: 70px; padding-bottom: 60px">
            <div class="row">
                <div class="col-xs-12">
                    <div class="col-md-5-5" style="padding: 0px; position: relative">
                        <div style="font-family: Raleway;font-size: 20pt;color: white;position: absolute; left: 31%; top: 40%; border-bottom: solid 1px white; padding-bottom: 20px"><a href="#">ENCH&Egrave;RE X</a></div>
                        <img src="/Content/images/horse_1.png" style="width:100%;max-height: 368px" />
                    </div>
                    <div class="col-md-0-5" style="padding: 0px">&nbsp;</div>
                    <div class="col-md-5-5" style="padding: 0px; position: relative">
                        <div style="font-family: Raleway;font-size: 20pt;color: white;position: absolute; left: 31%; top: 40%; border-bottom: solid 1px white; padding-bottom: 20px"><a href="#">ENCH&Egrave;RE Y</a></div>
                        <img src="/Content/images/horse_2.png" style="width:100%;max-height: 368px"/>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section -->

<script type="text/javascript">
    function imgError(el){
        $(el).remove();
    }   
</script>
