<section id="section-banner" style="margin-top: 0px;">
    <div class="shell">
        <div class="section-inner">
            <header class="section-head">
                <h2 class="letter-spacing-10" style="margin-bottom: 35px;font-family: Lato; font-size: 23pt; line-height: 18pt; color: #dbdbd9;"><?php echo $this->translate((($this->enchere)?$this->enchere->title:""), $this->lang_id); ?></h2>
                <img src="<?php echo $this->basePath() ?>/images/section-concept-filet.png" alt="" id="concept-filet">
            </header>
        </div>
    </div>
</section>

<section class="section" id="section-summary" style="margin: 0 50px; background: white;margin-top: -30px">
    <div class="shell">
        <header class="section-head" style=";padding: 0px; margin: 0px">
            <h2><span><?php echo $this->translate("Nos lots", $this->lang_id);?></span></h2>
            <h3 class="section-summary-soustitre"><?php echo $this->translate("Il y a", $this->lang_id)." ".count($this->lots)." ".$this->translate("lots dans cette enchère", $this->lang_id); ?></h3>
			<!--<div class="col-md-12 sous-titre"> @Model.Description</div>-->
			<div class="col-md-12 sous-titre"><?php echo $this->translate("Première vente aux enchères en ligne de foals de CSO d'exception.<br/>Ouverture des ventes le 26 Octobre 2016, possibilité d'enchérir à partir du 30 Octobre à 20h00, fin des enchères le 2 Novembre à 20h00.", $this->lang_id); ?></div>
        </header>
        <div class="row recherche_lots">
            <div class="col-xs-12" style="height:1px; border-top: solid 1px #ececec; margin-bottom: 15px;font-family: Lato;font-size: 18pt;">&nbsp;</div>
                <div class="row">
                    <div class="col-xs-12 margin">
                        <div class="col-xs-12 margin">
                            <div class="col-md-18">&nbsp;</div>
                            <div class="col-md-215" style="padding-left: 0px">
                                <a href="#"><div class="col-md-10" style="color:#e76558; border: solid 1px #e76558; line-height: 30px;font-family: Lato;font-size: 18pt;text-align: center;"><?php echo $this->translate("Tous", $this->lang_id); ?></div></a>
                            </div>
                            <div class="col-md-110" style="padding-left: 0px;font-family: Lato;font-size: 18pt;"><a href="#"><?php echo $this->translate("Père", $this->lang_id); ?></a></div>
                            <div class="col-md-125" style="padding-left: 0px;font-family: Lato;font-size: 18pt;"><a href="#"><?php echo $this->translate("Mère", $this->lang_id); ?></a></div>
                            <div class="col-md-176" style="padding-left: 0px;font-family: Lato;font-size: 18pt;"><a href="#"><?php echo $this->translate("Père de Mère", $this->lang_id); ?></a></div>
                            <div class="col-md-19" style="padding-left: 0px;">
                                <div class="" style="width: 140px;position: relative">
                                    <input type="text" id="search" style="border: none;border-bottom: solid 1px;width: 100%"/>
                                    <img src="<?php echo $this->basePath() ?>/images/icon_search.png" style="position: absolute;top: 0;right: 0px;"/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <div class="col-xs-12" style="height:1px; border-top: solid 1px #ececec; margin-top: 15px; margin-bottom: 40px;">&nbsp;</div>
        </div>
    </div>
</section>

<section class="section" id="section-lots" style="margin: 0 50px; background: white;">
    <div class="shell">
        <?php foreach($this->lots as $lot) { ?>
            <div class="section-body row lot-row">
                <div class="col-xs-12 margin">
                    <div class="col-md-3 ux-hover margin">
                        <div class="img-wrapper">
                            <a href="<?php echo $this->url("home/lots/lot", array("enchere_id" => $lot->enchere_id, "lot_id" => $lot->lot_id, 'lang'=>$this->lang_id)); ?>">
                                <!-- img src="@lot.Image" alt="" class="zoom" -->
                                <img src="<?php echo $this->basePath().$lot->image_url; ?>" alt="Photo non trouv&eacute;e" onerror="imgError(this)" class="zoom">
                            </a>
                        </div>
                    </div>
                    <div  class="col-md-05"> &nbsp</div>
                    <div class="col-md-456 coll-offset-2 margin">
                        <div class="row">
                            <div class="col-md-12">
                                <h3 class="col-xs-12 letter-spacing-5 auction-name"><?php echo $lot->title; ?></h3>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="col-xs-12">
                                    <img class="lot-filet" src="<?php echo $this->basePath() ?>/images/lot/lot-filet.png" alt="">
                                </div>
                            </div>
                            <div class="col-md-6" style="padding: 0px; margin-top: 20px;">
                                &nbsp;
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="col-xs-12 letter-spacing-2">
                                <?php if ($lot->pere && $lot->pere != null) {?>
                                    <div class="lot-features"><span><?php echo $this->translate("Père", $this->lang_id); ?> : </span><?php echo $lot->pere->name; ?></div>
                                <?php } if ($lot->mere && $lot->mere != null) { ?>
                                    <div class="lot-features"><span><?php echo $this->translate("Mère", $this->lang_id); ?> : </span><?php echo $lot->mere->name; ?></div>
                                <?php } if ($lot->pere_mere && $lot->pere_mere != null) { ?>
                                    <div class="lot-features last"><span><?php echo $this->translate("Père de mère", $this->lang_id); ?> : </span><?php echo $lot->pere_mere->name; ?></div>
                                <?php } ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-24 coll-offset-2 margin">
                        <div class="row">
                            <div class="col-md-12">
                                <!--<div class="price col-xs-12 margin"  style="font-family: Lato;  font-size:16pt; color:#000000; line-height:18.31pt">
                                    <span>@Ekestrian.Language.Lots.Resource.EstimatedPrice </span>15000
                                    <span>€</span> <sup>@Ekestrian.Language.Lots.Resource.HT</sup>
                                </div>-->
                            </div>
                        </div>
                        
                        <div class="row" style="margin-top: 46px;">
                            <div class="col-md-12">
                                <div class="col-xs-12 margin lot-sale-container">
                                    <!-- div class="auction-current" style="font-family: Lato; font-weight:regular; font-size:14pt; color:#e76558; line-height: 18pt"> 
                                        @Ekestrian.Language.Lots.Resource.ActualAuctionLabel<br>
                                        <span>
                                            <span style="font-family: Lato-bold; font-weight:bold; font-size:18pt; color:#e76558; line-height: 18.31pt">- €</span>
                                            <sup>@Ekestrian.Language.Lots.Resource.HT</sup>
                                        </span>
                                    </div>
                                    <div class="time"> @lot.RemainingTime </div -->
                                    <div class="btn-container" style="margin-top: 15px">
                                        <?php if($this->can_enchere == true && $lot->cloture == 0) { ?>
                                            <?php if($this->is_membre_co == false) { ?>
                                                <a href="<?php echo $this->url('home/membre', array('lang'=>$this->lang_id)); ?>">
                                                    <div class="mb5 btn btn-ekestrian-fill" style="font-family: Lato; font-weight:regular; font-size:12pt; color:white">
                                                        <?php echo $this->translate("Enchérir", $this->lang_id); ?>
                                                    </div>
                                                </a>
                                            <?php } else { ?>
                                                <a href="#" id="lien_enchere" data-enchere-id="<?php echo $lot->enchere_id; ?>" data-lot-id="<?php echo $lot->lot_id; ?>" >
                                                    <div class="mb5 btn btn-ekestrian-fill" style="font-family: Lato; font-weight:regular; font-size:12pt; color:white">
                                                        <?php echo $this->translate("Enchérir", $this->lang_id); ?>
                                                    </div>
                                                </a>

                                            <?php } ?>
										<?php } ?>
										
                                    </div>
                                    <div class="btn-container">
                                        <div class="btn-ekestrian-alt">
                                            <a href="<?php echo $this->url("home/lots/lot", array("enchere_id" => $lot->enchere_id, "lot_id" => $lot->lot_id, 'lang'=>$this->lang_id)); ?>" style="font-family: Lato; font-weight:normal;font-style: normal; font-size:12pt; color:#e76558">
                                                <?php echo $this->translate("Voir ce lot", $this->lang_id); ?>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
    <?php if($this->can_enchere == true) { ?>
	<div class="dialog_enchere" style="font-family: Lato">
		<div class="row" style="margin: 0">
			<div class="col-xs-12 actual_amount" style="text-align:center"></div>
			<br/>
			<div class="col-xs-12 success" style="text-align:center; color: green"></div>
			<div class="col-xs-12 alerte" style="text-align:center; color: red"></div>
			<br/>
			<div class="col-xs-12 enchere" style="text-align:center;">
				<div class="col-xs-10 enchere" style="text-align:center;float: none; margin: auto; border: solid 1px black">
					<div class="col-xs-12"style="z-index: 1001;background: white;margin-top: -10px;margin-bottom: 20px;"><?php echo $this->translate("PLACER UNE ENCH&Egrave;RE", $this->lang_id); ?></div>
					<div class="row" style="padding-bottom: 10px;">
						<div class="col-xs-12">
							<div class="col-xs-5" style="padding: 0px;">
								<select name="amount" style="height: 24px;"></select>
							</div>
							<div class="col-xs-2" style="padding: 0px;line-height: 24px;">EUR</div>
							<div class="col-xs-5" style="padding: 0px">
								<input type="button" value="ENCH&Egrave;RIR" style="background: transparent;border: solid 1px black;padding: 2px;"/>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="dialog_validation_enchere" style="font-family: Lato">
		<div class="row" style="margin: 0">
			<div class="col-xs-12 content" style="text-align:center"></div>
		</div>
	</div>
    <?php } ?>
</section>

<!-- section class="section" id="section-other-lots" style="margin: 0 50px; margin-top: 25px; background: white;">
    <div class="shell">
        <header class="section-head" style=";padding: 0px; margin: 0px">
            <h2><span>D&eacute;COUVREZ NOS AUTRES VENTES
</span></h2>
        </header>
        <div class="section-body section-body-ply col-md-12" style="padding: 0px;margin-top: 70px; padding-bottom: 60px">
            <div class="row">
                <div class="col-xs-12">
                    <div class="col-md-5-5" style="padding: 0px; position: relative">
                        <div style="font-family: Raleway;font-size: 20pt;color: white;position: absolute; left: 31%; top: 40%; border-bottom: solid 1px white; padding-bottom: 20px"><a href="#">ENCH&Egrave;RE X</a></div>
                        <img src="/Content/images/horse_1.png" style="width:100%;max-height: 368px" />
                    </div>
                    <div class="col-md-0-5" style="padding: 0px">&nbsp;</div>
                    <div class="col-md-5-5" style="padding: 0px; position: relative">
                        <div style="font-family: Raleway;font-size: 20pt;color: white;position: absolute; left: 31%; top: 40%; border-bottom: solid 1px white; padding-bottom: 20px"><a href="#">ENCH&Egrave;RE Y</a></div>
                        <img src="/Content/images/horse_2.png" style="width:100%;max-height: 368px"/>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section -->

<script type="text/javascript">
    function imgError(el){
        $(el).remove();
    }   
	
    
    $(document).ready(function(){
        <?php if($this->can_enchere == true) { ?>
            $('.dialog_enchere').dialog({
                autoOpen: false,
                minWidth: 500,
                minHeight: 310
            });

            $('.dialog_validation_enchere').dialog({
                autoOpen: false,
                minWidth: 500,
                minHeight: 310
            });

            $('.dialog_enchere input[type="button"]').unbind('click').on('click', function(e){
                var el = this;
                e.preventDefault();
                $.ajax({
                    url: '/<?php echo $this->lang_id; ?>/enchere/'+$(el).attr('data-enchere-id')+'/lot/'+$(el).attr('data-lot-id')+'/validation',
                    dataType: 'json',
                    data: {"value":$('.dialog_enchere select').val()},
                }).always(function () {
                }).done(function (result) {
                    if(result.status && result.status == 1) {
                        /*$('.dialog_enchere .alerte').empty();
                        $(".dialog_enchere select option").remove();
                        $('.dialog_enchere .success').empty().html("<?php echo $this->translate("Enchère enregistrée, un mail de confirmation vient de vous être envoyé", $this->lang_id); ?>");
                        /* mise en place de actual_amount *\/
                        var actuel = parseFloat((result.data.auction)?result.data.auction.value:result.data.lot.min_price);
                        $('.dialog_enchere .actual_amount').empty().html("<?php echo $this->translate('Enchère actuelle', $this->lang_id); ?> : "+actuel+" EUR");

                        if(actuel <= result.data.lot.reserve_price){
                            $('.dialog_enchere .alerte').empty().html("<?php echo $this->translate('Prix de reserve atteint', $this->lang_id); ?>");
                        }   

                        var pas = parseFloat((result.data.lot.ist_price && result.data.lot.ist_price > 0)?result.data.lot.ist_price : 1);
                        var i = 1;
                        while(i != 10) {
                            actuel = actuel + pas;
                            $(".dialog_enchere select").append('<option value="'+(actuel)+'">'+(actuel)+'</option>');
                            i++;
                        }*/
                        $('.dialog_enchere').dialog('close');
                        $('.dialog_validation_enchere .content').empty().html("<?php echo $this->translate("Enchère enregistrée, un mail de confirmation vient de vous être envoyé à l'adresse : ", $this->lang_id); ?>"+result.data.email);
                        $('.dialog_validation_enchere').dialog('open');
                        setTimeout(function(){ $('.dialog_validation_enchere').dialog('close'); }, 10000);
                    } else {
                        $('.dialog_enchere .alerte').empty().html(result.data);
                    }
                });
            });
        <?php } ?>
    });
    
    /* Mise en place de l'enchère */
    <?php if($this->can_enchere == true) { ?>    
        $('#lien_enchere').unbind('click').on('click', function(e){
            e.preventDefault();
            var el = this;
            $.ajax({
                url: '/<?php echo $this->lang_id; ?>/enchere/'+$(el).attr('data-enchere-id')+'/lot/'+$(el).attr('data-lot-id')+'/information',
                dataType: 'json',
                context: $(this)[0]
            }).always(function () {
            }).done(function (result) {
                if(result.status && result.status == 1) {
                    /* mise en place de actual_amount */
                    var actuel = parseFloat((result.data.auction)?result.data.auction.value:result.data.lot.min_price);
                    $('.dialog_enchere .actual_amount').empty().html("<?php echo $this->translate('Enchère actuelle', $this->lang_id); ?> : "+actuel+" EUR");

                    if(actuel <= result.data.lot.reserve_price){
                        $('.dialog_enchere .alerte').empty().html("<?php echo $this->translate('Prix de reserve atteint', $this->lang_id); ?>");
                    }   

                    var pas = parseFloat((result.data.lot.ist_price && result.data.lot.ist_price > 0)?result.data.lot.ist_price : 1);
                    var i = 1;
                    while(i != 10) {
                        actuel = actuel + pas;
                        $(".dialog_enchere select").append('<option value="'+(actuel)+'">'+(actuel)+'</option>');
                        i++;
                    }
                    $('.dialog_enchere input[type="button"]').attr('data-enchere-id', $(el).attr('data-enchere-id'));
                    $('.dialog_enchere input[type="button"]').attr('data-lot-id', $(el).attr('data-lot-id'));
                    $('.dialog_enchere').dialog('open');
                } else {
                    alert(result.data);
                }
            });
        });
    <?php } ?>
</script>
