<div class="main">
    <section id="section-concept" style="margin-top: 0px">
        <div class="shell">
            <div class="section-inner">
                <header class="section-head">
                    <!-- img src="<?php echo $this->basePath() ?>/images/section-concept-filet.png" alt="" id="concept-filet" -->
                </header>
            </div>
        </div>
    </section>
    
    <section class="section" id="section-auction" style="margin: 0 50px; background: white;margin-top: -30px; padding-bottom: 60px;">
        <div class="shell" style="max-width: 830px">
            <div class="section-head" style=";padding: 0px; margin: 0px">
                <h2 class="letter-spacing-10"><span><?php echo $this->translate("Nos partenaires", $this->lang_id); ?></span></h2>
            </div>
            <div class="section-body section-body-ply row" style="padding: 0px; margin: 0 -15px">
                <div class="row">
                    <div class="col-xs-5">
                        <img style="max-height: 200px;width: auto;" src="<?php echo $this->basePath()?>/img/caracolf.png" />
                    </div>
                    <div class="col-xs-7">
                        <div style="text-align: center"><h3 style="margin-bottom: 30px;" class="auction-name">~ www.caracole.fr ~</h3></div>
                        <div><?php echo $this->translate("CARACOLE crée des bijoux exceptionnels qui allient le crin de cheval avec les métaux précieux.", $this->lang_id); ?></div><br/>
                        <div><?php echo $this->translate("Ces pièces uniques permettent aux clients Caracole de porter ce lien privilégié où qu'ils aillent", $this->lang_id); ?></div>
                    </div>
                </div>
                
                <div class="row" style="padding-top: 80px">
                    <div class="col-xs-5">
                        <div style="text-align: center"><h3 style="margin-bottom: 30px;" class="auction-name">~ www.vetbiobank.com ~</h3></div>
                        <div><?php echo $this->translate("Depuis 5 ans, Vetbiobank est le partenaire des principaux haras qui utilisent la technologie des cellules souches néonatales (OMBISTEM) pour traiter les lésions articulaires de leurs jeunes chevaux. Vetbiobank a traité plus de 500 chevaux, en France et à l’international, avec des résultats cliniques à la hauteur de vos exigences", $this->lang_id); ?></div>
                    </div>
                    <div class="col-xs-7">
                        <img src="<?php echo $this->basePath()?>/img/vetbiobank.png" />
                    </div>
                </div>
                
                <div class="row" style="padding-top: 30px">
                    <div class="col-xs-6">
                        <img src="<?php echo $this->basePath()?>/img/pixio.png" />
                    </div>
                    <div class="col-xs-6">
                        <div style="text-align: center"><h3 style="margin-bottom: 30px;" class="auction-name">~ www.movensee.com ~</h3></div>
                        <div><?php echo $this->translate("PIXIO est la première \"caméra auto-follow\" qui filme en intérieur et en extérieur, jusqu'à 100m. PIXIO oriente la caméra vers la montre, filme, et zoome/dézoome automatiquement. Désormais vous pouvez filmer plus souvent, en toute indépendance, sans l'assistance d'un caméraman. Filmez du sport, des répétitions, des acteurs, des cérémonies, conférences, etc.", $this->lang_id); ?></div>
                    </div>
                </div> 
                
                <div class="row" style="padding-top: 30px">
                    <div class="col-xs-6">
                        <div style="text-align: center"><h3 style="margin-bottom: 30px;" class="auction-name">~ www.adecsif.fr ~</h3></div>
                        <div><?php echo $this->translate("Cette opération est soutenue par L’Association Des Chevaux de Sport d’Ile de France, représentée par Monsieur Patrick CLERIN. Aux portes de Paris, vous trouverez une sélection de chevaux et poneys, de sport et d’élevage, de grande qualité.  Ces éleveurs se sont fédérés autour de 3 principes communs : sélection rigoureuse, origines prestigieuses, élevages soigneux.", $this->lang_id); ?></div>
                    </div>
                    <div class="col-xs-6">
                        <img style="max-height: 300px;width: auto;" src="<?php echo $this->basePath()?>/img/adecsif.png" />
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>