<?php

$form = $this->form;
$form->prepare();
$elements = $form->getElements();
?>
<div id="form-cheval-edit">
    <div class="portlet box green-haze">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-shopping-cart"></i><?php echo $this->form_title ?>
            </div>
        </div>
        <div class="portlet-body form">
            <?php foreach ($elements as $element): 
                echo "<div style='height: auto'>".$this->formRow($form->get($element->getName())).' <div style="clear: both">&nbsp;</div></div>';
                if($element->getName() == "image_url" && !empty($this->cheval['image_url'])) {
                    echo "<div style='width: 100%'><img style='margin-left: 30%;max-width: 200px' src='".$this->basePath()."/../".$this->cheval['image_url']."' /></div>";
                }
            endforeach;
            ?>

        </div>
    </div>
</div>
<script>
    jQuery(document).ready(function() {

    });
</script>

