<?php

$form = $this->form;
$form->prepare();
$elements = $form->getElements();
?>
<div id="form-cheval-edit">
    <div class="portlet box green-haze">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-shopping-cart"></i><?php echo $this->form_title ?>
            </div>
        </div>
        <div class="portlet-body form">
            <?php foreach ($elements as $element): 
                echo "<div style='height: auto'>".$this->formRow($form->get($element->getName())).' <div style="clear: both">&nbsp;</div></div>';
            endforeach;
            ?>
            <div>&nbsp;</div>
        </div>
    </div>
    </div>
<script>
    jQuery(document).ready(function() {
        CKEDITOR.config.height = 150;
        CKEDITOR.config.width = 'auto';
        
        CKEDITOR.replace( 'translate_form_code' );
        CKEDITOR.replace( 'translate_form_valeur' );
    });
</script>

