<?php

$flashMessages = $this->flashMessages;//    flashMessenger()->getMessages();

echo $this->doctype(); ?>
<!--
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.1.1
Version: 2.0.2
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="<?php echo $this->lang_id.'-'.strtoupper($this->lang_id); ?>" class="no-js">
    <head>
           <base target="_self" href="<?php echo "http".(isset($_SERVER['HTTPS']) ? "s" : null)."://".$_SERVER["HTTP_HOST"]; ?>" target="_blank">
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Elite Auction Ekestrian', $this->lang_id))->setSeparator(' - ')->setAutoEscape(false) ?>
        <!-- BEGIN GLOBAL MANDATORY STYLES -->
        <link rel="shortcut icon" type="image/x-icon" href="http://www.ekestrian.com/ekestrian/images/favicon.png" />
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
        <!--link href="http://vjs.zencdn.net/4.12/video-js.css" rel="stylesheet" -->
        <meta name="robots" content="noindex,nofollow">

        <?php
            echo $this->headLink()->appendStylesheet($this->basePath() . '/css/mainstyle.css');
            echo $this->headLink()->appendStylesheet($this->basePath() . '/css/lightgallery.css'); 
            echo $this->headLink()->appendStylesheet($this->basePath() . '/css/blueimp-gallery.min.css'); 
            echo $this->headLink()->appendStylesheet($this->basePath() . '/css/jquery-ui.min.css'); 
			echo $this->headLink()->appendStylesheet($this->basePath() . '/css/bootstrap-datepicker3.css'); 
        ?>
        <!-- END THEME STYLES -->

        <!-- Scripts -->
        <?php
        
        $index = 0;
        foreach($this->headScript()->getIterator() as $js) {
            if(isset($js->attributes['src'])) {
                $this->headScript()->offsetSetFile($index, $this->basePath() . $js->attributes['src']);
            }
            $index++;
        }

        echo $this->headScript();
        ?>
    </head>

    <!-- BEGIN BODY -->
    <body style="background-color:#f2f2f2">
        <?php echo $this->flashMessenger()
            ->setMessageOpenFormat('<div%s><p>')
            ->setMessageSeparatorString('</p><p>')
            ->setMessageCloseString('</p></div>')
            ->render('success'); ?>
        
        <div class="wrapper">            
            <?php echo $this->navbar2; ?>
            
            <?php if (isset($flashMessages)) : ?>
                <?php foreach ($flashMessages as  $messages) :
                    foreach ($messages as $error_type => $message) :
                        foreach ($message as $m) :
                            switch($error_type){
                                case $this->message_error:
                                $class = 'alert-danger';
                                break;
                                case $this->message_success:
                                $class = 'alert-success';
                                break;
                                case $this->message_warning:
                                $class = 'alert-warning';
                                break;
                            }
                            ?>
                            <div class="app-alerts alert <?php echo $class ?> fade in">
                                <button aria-hidden="true" data-dismiss="alert" class="close" type="button"></button><?php echo $m ?>
                            </div>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            <?php endif; ?>
            
            <?php echo $this->content; ?>
            <?php echo $this->newsletter; ?>
            <?php echo $this->footer; ?>

            <script type="text/javascript">
                $(document).ready(function () {
                if($.cookie('AuthCookie'))    {
                    $("#authenticated").show();
                } else {
                        $("#anonymous").show();
                    }
                });

                $("img.zoom").elevateZoom();
            </script>            
        </div>
        
        <input id="base-url" type="hidden" value="<?php echo $this->basePath() ?>" />
    </body>
    <!-- END BODY -->

</html>
